__author__ = 'Daniel Ward'
__copyright__ = 'Copyright 2025, Daniel Ward'
__license__ = 'GPL v3'
__version__ = 'tres leches'

#   S&P500 + NASDAQ500
composite_index = ('SPY', 'QQQ',
    'A', 'AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABNB', 'ABT', 'ACGL', 'ACN',
    'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AFL', 'AIG',
    'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK', 'ALL', 'ALLE', 'AMAT', 'AMCR',
    'AMD', 'AME', 'AMGN', 'AMP', 'AMT', 'AMZN', 'ANET', 'ANSS', 'AON', 'AOS',
    'APA', 'APD', 'APH', 'APTV', 'ARE', 'ASML', 'ATO', 'AVB', 'AVGO',
    'AVY', 'AWK', 'AXON', 'AXP', 'AZN', 'AZO', 'BA', 'BAC', 'BALL', 'BAX',
    'BBWI', 'BBY', 'BDX', 'BEN', 'BG', 'BIIB', 'BIO', 'BK', 'BKNG',
    'BKR', 'BLK', 'BMY', 'BR', 'BRO', 'BSX', 'BWA', 'BXP', 'C', 'CAG',
    'CAH', 'CARR', 'CAT', 'CB', 'CBOE', 'CBRE', 'CCI', 'CCL', 'CDAY', 'CDNS',
    'CDW', 'CE', 'CF', 'CFG', 'CHD', 'CHRW', 'CHTR', 'CI', 'CINF', 'CL',
    'CLX', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF',
    'COO', 'COP', 'COST', 'CPB', 'CPRT', 'CPT', 'CRL', 'CRM', 'CRWD', 'CSCO',
    'CSGP', 'CSX', 'CTAS', 'CTLT', 'CTRA', 'CTSH', 'CTVA', 'CVS', 'CVX', 'CZR',
    'D', 'DAL', 'DD', 'DDOG', 'DE', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS',
    'DISH', 'DLR', 'DLTR', 'DOV', 'DOW', 'DPZ', 'DRI', 'DTE', 'DUK', 'DVA',
    'DVN', 'DXC', 'DXCM', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EIX', 'EL', 'ELV',
    'EMN', 'EMR', 'ENPH', 'EOG', 'EPAM', 'EQIX', 'EQR', 'EQT', 'ES', 'ESS',
    'ETN', 'ETR', 'ETSY', 'EVRG', 'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'F',
    'FANG', 'FAST', 'FCX', 'FDS', 'FDX', 'FE', 'FFIV', 'FICO', 'FIS', 'FISV',
    'FITB', 'FLT', 'FMC', 'FOX', 'FOXA', 'FRT', 'FSLR', 'FTNT', 'FTV', 'GD',
    'GE', 'GEHC', 'GEN', 'GFS', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GNRC',
    'GOOG', 'GOOGL', 'GPC', 'GPN', 'GRMN', 'GS', 'GWW', 'HAL', 'HAS', 'HBAN',
    'HCA', 'HD', 'HES', 'HIG', 'HII', 'HLT', 'HOLX', 'HON', 'HPE', 'HPQ', 'HRL',
    'HSIC', 'HST', 'HSY', 'HUM', 'HWM', 'IBM', 'ICE', 'IDXX', 'IEX', 'IFF',
    'ILMN', 'INCY', 'INTC', 'INTU', 'INVH', 'IP', 'IPG', 'IQV', 'IR', 'IRM',
    'ISRG', 'IT', 'ITW', 'IVZ', 'J', 'JBHT', 'JCI', 'JD', 'JKHY', 'JNJ', 'JNPR',
    'JPM', 'K', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KLAC', 'KMB', 'KMI', 'KMX',
    'KO', 'KR', 'L', 'LCID', 'LDOS', 'LEN', 'LH', 'LHX', 'LIN', 'LKQ', 'LLY',
    'LMT', 'LNC', 'LNT', 'LOW', 'LRCX', 'LULU', 'LUV', 'LVS', 'LW', 'LYB',
    'LYV', 'MA', 'MAA', 'MAR', 'MAS', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ',
    'MDT', 'MELI', 'MET', 'META', 'MGM', 'MHK', 'MKC', 'MKTX', 'MLM', 'MMC',
    'MMM', 'MNST', 'MO', 'MOH', 'MOS', 'MPC', 'MPWR', 'MRK', 'MRNA', 'MRO',
    'MRVL', 'MS', 'MSCI', 'MSFT', 'MSI', 'MTB', 'MTCH', 'MTD', 'MU', 'NCLH',
    'NDAQ', 'NDSN', 'NEE', 'NEM', 'NFLX', 'NI', 'NKE', 'NOC', 'NOW', 'NRG',
    'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NVR', 'NWL', 'NWS', 'NWSA', 'NXPI',
    'O', 'ODFL', 'OGN', 'OKE', 'OMC', 'ON', 'ORCL', 'ORLY', 'OTIS', 'OXY',
    'PANW', 'PARA', 'PAYC', 'PAYX', 'PCAR', 'PCG', 'PDD', 'PEAK', 'PEG', 'PEP',
    'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PKI', 'PLD', 'PM', 'PNC',
    'PNR', 'PNW', 'PODD', 'POOL', 'PPG', 'PPL', 'PRU', 'PSA', 'PSX', 'PTC',
    'PWR', 'PXD', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'RE', 'REG', 'REGN', 'RF',
    'RHI', 'RIVN', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST', 'RSG',
    'RTX', 'SBAC', 'SBUX', 'SCHW', 'SEDG', 'SEE', 'SGEN', 'SHW', 'SIRI', 'SJM',
    'SLB', 'SNA', 'SNPS', 'SO', 'SPG', 'SPGI', 'SRE', 'STE', 'STLD', 'STT',
    'STX', 'STZ', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TDG', 'TDY',
    'TEAM', 'TECH', 'TEL', 'TER', 'TFC', 'TFX', 'TGT', 'TJX', 'TMO', 'TMUS',
    'TPR', 'TRGP', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTWO',
    'TXN', 'TXT', 'TYL', 'UAL', 'UDR', 'UHS', 'ULTA', 'UNH', 'UNP', 'UPS',
    'URI', 'USB', 'V', 'VFC', 'VICI', 'VLO', 'VMC', 'VRSK', 'VRSN', 'VRTX',
    'VTR', 'VTRS', 'VZ', 'WAB', 'WAT', 'WBA', 'WBD', 'WDAY', 'WDC', 'WEC',
    'WELL', 'WFC', 'WHR', 'WM', 'WMB', 'WMT', 'WRB', 'WRK', 'WST', 'WTW',
    'WY', 'WYNN', 'XEL', 'XOM', 'XRAY', 'XYL', 'YUM', 'ZBH', 'ZBRA', 'ZION',
    'ZM', 'ZS', 'ZTS',
    )


#  small cap+ $10-$50
small_cap = (
    'AA', 'AAL', 'ABR', 'ACAD', 'ACIW', 'ACMR', 'ADMA', 'ADNT', 'AEHR', 'AEO',
    'AES', 'AGIO', 'AGR', 'AGS', 'AKR', 'AKRO', 'AL', 'ALK', 'ALLY', 'AM',
    'AMH', 'AMKR', 'AMRC', 'AMRK', 'AMSC', 'APA', 'APG', 'APLE', 'APLS',
    'APPN', 'AR', 'ARCC', 'ARCT', 'ARLO', 'ARMK', 'AROC', 'ARR', 'ARVN',
    'ARWR', 'ASB', 'ASPN', 'ATEC', 'ATEN', 'ATRC', 'AVTR', 'AXTA', 'BAC',
    'BANC', 'BAX', 'BBWI', 'BE', 'BEN', 'BFH', 'BHVN', 'BKR', 'BKU',
    'BL', 'BLMN', 'BMY', 'BOX', 'BRX', 'BTU', 'BV', 'BWA', 'BXMT', 'BYON',
    'CADE', 'CAG', 'CAKE', 'CAL', 'CALX', 'CARG', 'CBRL', 'CC', 'CCL', 'CDNA',
    'CDP', 'CENX', 'CFG', 'CG', 'CGNX', 'CHWY', 'CHX', 'CIEN', 'CIM', 'CLDX',
    'CLF', 'CLSK', 'CMA', 'CMCSA', 'CMP', 'CNK', 'CNNE', 'CNO', 'CNP', 'CNX',
    'COLB', 'COLD', 'CORT', 'COTY', 'CPB', 'CPRX', 'CRK', 'CRNX', 'CSCO', 'CSX',
    'CTRA', 'CTRE', 'CUBE', 'CUZ', 'CVBF', 'CVI', 'CWEN', 'CWH', 'CXW', 'CZR',
    'D', 'DAL', 'DAN', 'DAR', 'DAY', 'DBRG', 'DBX', 'DEA', 'DEI', 'DK', 'DNLI',
    'DNOW', 'DOC', 'DRS', 'DVAX', 'DVN', 'DX', 'DXC', 'EFC', 'ELAN', 'ELME',
    'ENLC', 'ENOV', 'EOLS', 'EPD', 'EPR', 'EPRT', 'EQC', 'EQH', 'EQT', 'ESI',
    'ET', 'ETRN', 'EVBG', 'EVH', 'EXAS', 'EXC', 'EXEL', 'EXLS', 'EXPI', 'EXTR',
    'EYE', 'EZPW', 'F', 'FBP', 'FCX', 'FE', 'FHB', 'FHI', 'FHN', 'FIBK', 'FITB',
    'FIVN', 'FL', 'FLEX', 'FLO', 'FLR', 'FLS', 'FNB', 'FNF', 'FOX', 'FOXA',
    'FOXF', 'FR', 'FSK', 'FTDR', 'FTI', 'FULT', 'FWRD', 'GBCI', 'GBDC', 'GEN',
    'GEO', 'GH', 'GIII', 'GLPI', 'GLW', 'GM', 'GME', 'GNK', 'GNTX', 'GO', 'GPK',
    'GPRE', 'GPS', 'GRPN', 'GSBD', 'GT', 'GTES', 'HA', 'HAL', 'HASI', 'HBAN',
    'HESM', 'HGV', 'HIW', 'HLF', 'HLIT', 'HLX', 'HOG', 'HOMB', 'HOPE', 'HP',
    'HPE', 'HPQ', 'HR', 'HRL', 'HST', 'HTGC', 'HUN', 'HUT', 'IAC', 'IART',
    'IDYA', 'IEP', 'IMVT', 'INOD', 'INTC', 'INVA', 'INVH', 'IONS', 'IP', 'IPG',
    'IRDM', 'IRT', 'IVZ', 'JBGS', 'JEF', 'JELD', 'JNPR', 'JWN', 'KAR', 'KDP',
    'KEY', 'KHC', 'KIM', 'KMI', 'KMT', 'KN', 'KNX', 'KR', 'KRC', 'KRG', 'KSS',
    'KTOS', 'KURA', 'LAUR', 'LAZ', 'LBRT', 'LEG', 'LEVI', 'LITE', 'LKQ', 'LNC',
    'LPG', 'LQDA', 'LSXMA', 'LSXMK', 'LUV', 'LVS', 'LYFT', 'M', 'MAC', 'MARA',
    'MAT', 'MCS', 'MDU', 'METC', 'MFA', 'MGM', 'MGNI', 'MGY', 'MITK', 'MLKN',
    'MNRO', 'MO', 'MODG', 'MODN', 'MOS', 'MPLX', 'MRC', 'MRO', 'MTCH', 'MTG',
    'MUR', 'MWA', 'MXL', 'MYGN', 'NAVI', 'NCLH', 'NEM', 'NEO', 'NEOG', 'NEP',
    'NFE', 'NI', 'NLY', 'NMIH', 'NMRK', 'NNN', 'NOG', 'NOV', 'NSA', 'NTCT',
    'NTLA', 'NUS', 'NVAX', 'NWBI', 'NWS', 'NWSA', 'OCSL', 'OGE', 'OHI', 'OI',
    'OII', 'OLN', 'OMF', 'OMI', 'ONB', 'OPCH', 'ORI', 'OUT', 'OVV', 'OZK',
    'PAA', 'PAGP', 'PARA', 'PARR', 'PBF', 'PCG', 'PCRX', 'PD', 'PDCO', 'PEB',
    'PENN', 'PFE', 'PFLT', 'PFS', 'PINC', 'PINS', 'PK', 'PLAY', 'PMT', 'PNM',
    'POR', 'PPBI', 'PPC', 'PPL', 'PR', 'PRDO', 'PTCT', 'PTEN', 'PTGX',
    'PZZA', 'QDEL', 'RAMP', 'RARE', 'RCKT', 'RCM', 'RCUS', 'RDN', 'REVG',
    'REXR', 'REZI', 'RF', 'RGNX', 'RGP', 'RILY', 'RITM', 'RNG', 'ROIC', 'ROL',
    'RPAY', 'RPD', 'RRC', 'RUN', 'RVLV', 'RYTM', 'SAGE', 'SATS', 'SAVA', 'SBH',
    'SBOW', 'SBRA', 'SCS', 'SEE', 'SEM', 'SGH', 'SGRY', 'SHO', 'SHOO', 'SILK',
    'SITC', 'SIX', 'SKT', 'SLB', 'SLCA', 'SLGN', 'SLM', 'SM', 'SMAR', 'SMPL',
    'SMTC', 'SNAP', 'SNDR', 'SNDX', 'SNV', 'SONO', 'SPR', 'ST', 'STAA', 'STAG',
    'STOK', 'STR', 'STWD', 'SUM', 'SUPN', 'SYF', 'T', 'TALO', 'TBBK', 'TDC',
    'TDOC', 'TDS', 'TENB', 'TFC', 'TGI', 'TGNA', 'TGTX', 'TNDM', 'TNL', 'TPC',
    'TPH', 'TPR', 'TPX', 'TRIP', 'TRN', 'TROX', 'TRUP', 'TTMI', 'TWO', 'TWST',
    'UAL', 'UDR', 'UE', 'UGI', 'UNFI', 'UPWK', 'URBN', 'URGN', 'USB',
    'UTI', 'UTZ', 'VCYT', 'VECO', 'VFC', 'VGR', 'VICI', 'VIRT', 'VNO', 'VNOM',
    'VRDN', 'VRE', 'VRNS', 'VRNT', 'VRRM', 'VSAT', 'VSH', 'VSTO', 'VTLE',
    'VTRS', 'VVV', 'VYX', 'VZ', 'WBA', 'WBS', 'WEN', 'WERN', 'WES', 'WKC',
    'WMB', 'WNC', 'WOLF', 'WRK', 'WSC', 'WTRG', 'WTTR', 'WU', 'WWW', 'WY', 'X',
    'XHR', 'XNCR', 'XPRO', 'XRAY', 'XRX', 'YELP', 'YETI', 'Z', 'ZG', 'ZION',
    'ZWS',
    )

#  over 300mln cap, over $10 price, over 1M average volume, IPO > 5 years
active_trading_index = (
    'A', 'AA', 'AAOI', 'AAP', 'AAPL', 'ABBV', 'ABR', 'ABT', 'ACAD', 'ACGL',
    'ACHC', 'ACM', 'ACMR', 'ACN', 'ADBE', 'ADC', 'ADI', 'ADM', 'ADMA', 'ADNT',
    'ADP', 'ADSK', 'AEE', 'AEM', 'AEO', 'AEP', 'AER', 'AES', 'AFL', 'AGI',
    'AIG', 'AJG', 'AKAM', 'AKR', 'AKRO', 'ALB', 'ALC', 'ALGN', 'ALK', 'ALKS',
    'ALL', 'ALLE', 'ALLY', 'ALV', 'AM', 'AMAT', 'AMD', 'AME', 'AMGN', 'AMH',
    'AMKR', 'AMN', 'AMT', 'AMX', 'AMZN', 'ANAB', 'ANET', 'ANF', 'AON', 'AOS',
    'APA', 'APD', 'APG', 'APH', 'APLE', 'APLS', 'APO', 'APTV', 'AR', 'ARCC',
    'ARE', 'ARES', 'ARMK', 'AROC', 'ARQT', 'ARR', 'ARWR', 'ASB', 'ASML',
    'ASTS', 'ATEC', 'ATEN', 'ATI', 'ATO', 'AU', 'AUB', 'AVGO', 'AVPT', 'AVT',
    'AVTR', 'AWK', 'AXP', 'AXTA', 'AZN', 'BA', 'BABA', 'BAC', 'BAH', 'BALL',
    'BAM', 'BANC', 'BAX', 'BBIO', 'BBVA', 'BBWI', 'BBY', 'BC', 'BCE', 'BCS',
    'BDX', 'BE', 'BEAM', 'BECN', 'BEN', 'BERY', 'BFH', 'BG', 'BHP',
    'BHVN', 'BIDU', 'BIIB', 'BILI', 'BILL', 'BJ', 'BK', 'BKR', 'BLDR', 'BMRN',
    'BMY', 'BN', 'BNS', 'BOOT', 'BOX', 'BP', 'BPMC', 'BRBR', 'BRKR',
    'BRO', 'BRX', 'BSX', 'BTI', 'BTU', 'BUD', 'BUR', 'BURL', 'BVN', 'BWA',
    'BWXT', 'BX', 'BXMT', 'BXP', 'BYD', 'C', 'CADE', 'CAG', 'CAH', 'CAKE',
    'CAL', 'CALM', 'CAPR', 'CAR', 'CARG', 'CARR', 'CAT', 'CB', 'CBRE', 'CBRL',
    'CC', 'CCEP', 'CCI', 'CCJ', 'CCK', 'CCL', 'CDNS', 'CDP', 'CDW', 'CE',
    'CELH', 'CENX', 'CF', 'CFG', 'CG', 'CGNX', 'CHD', 'CHKP', 'CHRW', 'CHTR',
    'CHWY', 'CHX', 'CI', 'CIEN', 'CIVI', 'CL', 'CLMT', 'CLS', 'CLX', 'CM',
    'CMA', 'CMC', 'CMCSA', 'CME', 'CMG', 'CMS', 'CNC', 'CNH', 'CNI', 'CNK',
    'CNP', 'CNQ', 'CNX', 'COF', 'COHR', 'COLB', 'COLD', 'COO', 'COP', 'COR',
    'CORT', 'COST', 'CP', 'CPB', 'CPRI', 'CPRT', 'CPRX', 'CPT', 'CRH', 'CRI',
    'CRK', 'CRL', 'CRM', 'CRNX', 'CROX', 'CRSP', 'CRWD', 'CSCO', 'CSGP',
    'CSIQ', 'CSX', 'CTAS', 'CTRA', 'CTRE', 'CTSH', 'CTVA', 'CUBE', 'CUK',
    'CUZ', 'CVE', 'CVI', 'CVNA', 'CVS', 'CVX', 'CWEN', 'CWH', 'CXW', 'CYTK',
    'CZR', 'D', 'DAL', 'DAN', 'DAR', 'DAY', 'DB', 'DBX', 'DD', 'DDOG', 'DE',
    'DECK', 'DEI', 'DELL', 'DEO', 'DESP', 'DFS', 'DG', 'DGX', 'DHI', 'DHR',
    'DHT', 'DINO', 'DIS', 'DK', 'DKNG', 'DKS', 'DLR', 'DLTR', 'DNLI', 'DNOW',
    'DOC', 'DOCU', 'DOV', 'DOW', 'DRI', 'DT', 'DTE', 'DUK', 'DVAX', 'DVN',
    'DX', 'DXC', 'DXCM', 'EA', 'EAT', 'EBAY', 'ECL', 'ED', 'EDU', 'EFC',
    'EFX', 'EGO', 'EH', 'EIX', 'EL', 'ELF', 'ELS', 'ELV', 'EMN', 'EMR',
    'ENB', 'ENPH', 'ENTG', 'EOG', 'EPD', 'EPRT', 'EQH', 'EQNR', 'EQR',
    'EQT', 'ERJ', 'ES', 'ESI', 'ESTC', 'ET', 'ETN', 'ETR', 'ETSY', 'EVRG',
    'EVRI', 'EW', 'EWBC', 'EXAS', 'EXC', 'EXEL', 'EXLS', 'EXPD', 'EXPE',
    'EXR', 'EXTR', 'EYE', 'EZPW', 'F', 'FANG', 'FAST', 'FBIN', 'FBP', 'FCX',
    'FDX', 'FE', 'FERG', 'FHN', 'FI', 'FIS', 'FITB', 'FIVE', 'FIVN', 'FL',
    'FLEX', 'FLG', 'FLO', 'FLR', 'FLS', 'FLUT', 'FMC', 'FNB', 'FND', 'FNF',
    'FOX', 'FOXA', 'FR', 'FRO', 'FRPT', 'FSK', 'FSLR', 'FTAI', 'FTI', 'FTNT',
    'FTV', 'FULT', 'FUN', 'FUTU', 'FWONK', 'G', 'GAP', 'GBDC', 'GD', 'GDDY',
    'GDS', 'GE', 'GEN', 'GEO', 'GES', 'GFI', 'GFL', 'GGAL', 'GH', 'GILD',
    'GIS', 'GLNG', 'GLPI', 'GLW', 'GM', 'GMAB', 'GME', 'GMED', 'GNTX', 'GO',
    'GOF', 'GOLD', 'GOOG', 'GOOGL', 'GPC', 'GPK', 'GPN', 'GRMN', 'GRPN',
    'GS', 'GSK', 'GT', 'GTES', 'H', 'HAL', 'HALO', 'HAS', 'HASI', 'HBAN',
    'HCA', 'HD', 'HDB', 'HES', 'HESM', 'HGV', 'HIG', 'HIMS', 'HIW', 'HLT',
    'HMC', 'HMY', 'HOG', 'HOLX', 'HOMB', 'HON', 'HOPE', 'HP', 'HPE', 'HPQ',
    'HQY', 'HR', 'HRB', 'HRL', 'HSBC', 'HSIC', 'HST', 'HSY', 'HTGC', 'HTHT',
    'HUM', 'HUN', 'HUT', 'HWM', 'HXL', 'IAC', 'IBKR', 'IBM', 'IBN', 'ICE',
    'ICLR', 'IDYA', 'IFF', 'IGT', 'ILMN', 'IMVT', 'INCY', 'INDV', 'INFY',
    'ING', 'INMD', 'INOD', 'INSM', 'INTC', 'INTU', 'INVH', 'IONS', 'IP',
    'IPG', 'IQV', 'IR', 'IRDM', 'IRM', 'IRT', 'ISRG', 'ITW', 'IVZ', 'JAZZ',
    'JBGS', 'JBHT', 'JBL', 'JCI', 'JD', 'JEF', 'JHG', 'JHX', 'JNJ', 'JNPR',
    'JPM', 'JWN', 'K', 'KBH', 'KBR', 'KDP', 'KEY', 'KEYS', 'KGC', 'KHC',
    'KIM', 'KKR', 'KLAC', 'KMB', 'KMI', 'KMT', 'KMX', 'KNX', 'KO', 'KR',
    'KRC', 'KRG', 'KROS', 'KT', 'KTOS', 'LAZ', 'LBRT', 'LBTYA', 'LBTYK',
    'LC', 'LDOS', 'LEN', 'LEVI', 'LHX', 'LIN', 'LITE', 'LKQ', 'LLY',
    'LMT', 'LNC', 'LNG', 'LNT', 'LOW', 'LPLA', 'LRCX', 'LSCC', 'LSPD',
    'LULU', 'LUV', 'LVS', 'LW', 'LYB', 'LYFT', 'LYV', 'M', 'MA', 'MAC',
    'MANH', 'MAR', 'MARA', 'MAS', 'MAT', 'MC', 'MCD', 'MCHP', 'MDB',
    'MDLZ', 'MDT', 'MDU', 'MET', 'META', 'MFC', 'MGA', 'MGM', 'MGNI',
    'MGY', 'MKC', 'MKSI', 'MMC', 'MMM', 'MNST', 'MO', 'MOD', 'MOS', 'MPC',
    'MPLX', 'MPWR', 'MRK', 'MRNA', 'MRVL', 'MS', 'MSFT', 'MSTR', 'MT', 'MTB',
    'MTCH', 'MTDR', 'MTG', 'MTH', 'MTZ', 'MU', 'MUFG', 'MUR', 'MWA', 'MXL',
    'NBIS', 'NBIX', 'NCLH', 'NDAQ', 'NEA', 'NEE', 'NEM', 'NEO', 'NET', 'NFLX',
    'NI', 'NKE', 'NLY', 'NMRK', 'NNN', 'NOC', 'NOG', 'NOV', 'NOW', 'NRG',
    'NSC', 'NTAP', 'NTES', 'NTNX', 'NTR', 'NTRA', 'NTRS', 'NUE', 'NVDA',
    'NVO', 'NVS', 'NVST', 'NVT', 'NWG', 'NWSA', 'NXPI', 'NYT', 'O', 'OBDC',
    'OC', 'ODFL', 'OGE', 'OHI', 'OI', 'OII', 'OKE', 'OKTA', 'OLLI', 'OLN',
    'OMC', 'OMF', 'ON', 'ONB', 'ONTO', 'OPCH', 'ORCL', 'ORI', 'ORLA', 'OSW',
    'OTEX', 'OTIS', 'OUT', 'OVV', 'OXY', 'OZK', 'PAA', 'PAAS', 'PAGP', 'PANW',
    'PARA', 'PARR', 'PAYX', 'PBA', 'PBF', 'PBR', 'PCAR', 'PD', 'PDD',
    'PDI', 'PEG', 'PEGA', 'PENN', 'PEP', 'PFE', 'PFG', 'PFGC', 'PFLT', 'PG',
    'PGNY', 'PGR', 'PHM', 'PHYS', 'PII', 'PINC', 'PINS', 'PK', 'PLAY', 'PLD',
    'PLNT', 'PLYA', 'PM', 'PNC', 'PNR', 'PNW', 'POR', 'PPC', 'PPG', 'PPL',
    'PPTA', 'PR', 'PRGO', 'PRIM', 'PRMB', 'PRU', 'PSLV', 'PSN', 'PSTG', 'PSX',
    'PTC', 'PTGX', 'PUK', 'PVH', 'PWR', 'PYPL', 'PZZA', 'QCOM', 'QDEL',
    'QFIN', 'QGEN', 'QRVO', 'QSR', 'QURE', 'QXO', 'RBA', 'RCI', 'RCL', 'RDN',
    'RDY', 'REG', 'REXR', 'REZI', 'RF', 'RH', 'RHI', 'RHP', 'RIO', 'RITM',
    'RJF', 'RL', 'RMBS', 'RMD', 'RNG', 'ROK', 'ROKU', 'ROL', 'ROST', 'RRC',
    'RSG', 'RSI', 'RTX', 'RVLV', 'RVMD', 'RVTY', 'RY', 'RYAAY', 'RYN', 'SA',
    'SAP', 'SATS', 'SBLK', 'SBRA', 'SBS', 'SBUX', 'SCCO', 'SCHW', 'SCI',
    'SDGR', 'SE', 'SEDG', 'SEE', 'SEI', 'SFM', 'SGI', 'SGRY', 'SHAK', 'SHEL',
    'SHOO', 'SHOP', 'SHW', 'SIG', 'SIRI', 'SJM', 'SKX', 'SLB', 'SLM', 'SLNO',
    'SM', 'SMCI', 'SMFG', 'SMG', 'SMMT', 'SMTC', 'SNDX', 'SNPS', 'SNV', 'SNY',
    'SO', 'SONY', 'SPG', 'SPGI', 'SPOT', 'SPR', 'SQM', 'SRE', 'SRPT', 'SRRK',
    'SSNC', 'SSRM', 'ST', 'STAA', 'STAG', 'STLD', 'STM', 'STNE', 'STNG',
    'STT', 'STWD', 'STX', 'STZ', 'SU', 'SUPV', 'SW', 'SWK', 'SWKS', 'SWTX',
    'SYF', 'SYK', 'SYY', 'T', 'TAK', 'TAP', 'TCOM', 'TD', 'TDC', 'TDW',
    'TEAM', 'TECH', 'TECK', 'TEL', 'TENB', 'TER', 'TEVA', 'TEX', 'TFC',
    'TFX', 'TGI', 'TGNA', 'TGT', 'TGTX', 'THC', 'TJX', 'TKO', 'TMDX', 'TME',
    'TMHC', 'TMO', 'TMUS', 'TNDM', 'TOL', 'TPH', 'TPR', 'TREX', 'TRGP',
    'TRIP', 'TRMB', 'TROW', 'TRP', 'TRU', 'TRV', 'TS', 'TSCO', 'TSLA', 'TSM',
    'TSN', 'TT', 'TTC', 'TTD', 'TTE', 'TTEK', 'TTWO', 'TU', 'TVTX', 'TW',
    'TWLO', 'TWO', 'TWST', 'TXN', 'TXNM', 'TXRH', 'TXT', 'UAL', 'UBER', 'UBS',
    'UDR', 'UE', 'UGI', 'UL', 'ULTA', 'UNH', 'UNM', 'UNP', 'UPS', 'UPWK',
    'URBN', 'USB', 'USFD', 'UTZ', 'V', 'VEEV', 'VFC', 'VIAV', 'VICI', 'VIPS',
    'VIRT', 'VIST', 'VKTX', 'VLO', 'VMC', 'VNO', 'VNOM', 'VOYA', 'VRNA',
    'VRNS', 'VRRM', 'VRT', 'VRTX', 'VSH', 'VST', 'VTLE', 'VTR', 'VVV', 'VZ',
    'W', 'WAB', 'WAL', 'WBA', 'WBS', 'WCN', 'WDAY', 'WDC', 'WDS', 'WEC',
    'WELL', 'WEN', 'WES', 'WEX', 'WFC', 'WFRD', 'WH', 'WHR', 'WM', 'WMB',
    'WMT', 'WNC', 'WPC', 'WPM', 'WRB', 'WSC', 'WSM', 'WST', 'WTRG', 'WU',
    'WWW', 'WY', 'WYNN', 'X', 'XEL', 'XOM', 'XP', 'XPO', 'XRAY', 'XYL',
    'XYZ', 'YETI', 'YPF', 'YUM', 'YUMC', 'Z', 'ZBH', 'ZION', 'ZLAB', 'ZM',
    'ZS', 'ZTO', 'ZTS', 'ZWS',
    )

#   IPO > 5 years, Price > $2, NASDAQ & NYSE & AMEX
FULL_LIST = (
    'A', 'AA', 'AAAU', 'AADR', 'AAL', 'AAMI', 'AAOI', 'AAON',
    'AAP', 'AAPL', 'AAT', 'AAVM', 'AAXJ', 'AB', 'ABBV', 'ABCB',
    'ABEO', 'ABEQ', 'ABEV', 'ABFL', 'ABG', 'ABLG', 'ABM', 'ABR',
    'ABT', 'ABTS', 'ABUS', 'AC', 'ACA', 'ACAD', 'ACB', 'ACCO',
    'ACCS', 'ACEL', 'ACES', 'ACGL', 'ACHC', 'ACHV', 'ACIC', 'ACIO',
    'ACIW', 'ACLS', 'ACM', 'ACMR', 'ACN', 'ACNB', 'ACNT', 'ACP',
    'ACR', 'ACRE', 'ACSI', 'ACTG', 'ACU', 'ACV', 'ACWI', 'ACWV',
    'ACWX', 'ADBE', 'ADC', 'ADEA', 'ADI', 'ADM', 'ADMA', 'ADME',
    'ADNT', 'ADP', 'ADPT', 'ADSK', 'ADT', 'ADTN', 'ADUS', 'ADVM',
    'ADX', 'ADXN', 'AEE', 'AEF', 'AEG', 'AEHL', 'AEHR', 'AEIS',
    'AEM', 'AEO', 'AEP', 'AER', 'AES', 'AESR', 'AEVA', 'AEYE',
    'AFB', 'AFBI', 'AFG', 'AFIF', 'AFK', 'AFL', 'AFLG', 'AFMC',
    'AFSM', 'AFYA', 'AG', 'AGCO', 'AGD', 'AGEN', 'AGG', 'AGGY',
    'AGI', 'AGIO', 'AGM', 'AGNC', 'AGNG', 'AGO', 'AGQ', 'AGRO',
    'AGS', 'AGX', 'AGYS', 'AGZ', 'AGZD', 'AHCO', 'AHH', 'AHT',
    'AIA', 'AIEQ', 'AIFF', 'AIG', 'AIN', 'AIO', 'AIOT', 'AIQ',
    'AIR', 'AIRG', 'AIRI', 'AIRR', 'AIRT', 'AIT', 'AIV', 'AIVC',
    'AIVI', 'AIVL', 'AIZ', 'AJG', 'AKAM', 'AKBA', 'AKR', 'AKRO',
    'AL', 'ALAR', 'ALB', 'ALBT', 'ALC', 'ALCO', 'ALDX', 'ALE',
    'ALEX', 'ALG', 'ALGN', 'ALGT', 'ALK', 'ALKS', 'ALL', 'ALLE',
    'ALLT', 'ALLY', 'ALNT', 'ALNY', 'ALOT', 'ALRM', 'ALRS', 'ALSN',
    'ALT', 'ALTG', 'ALTS', 'ALTY', 'ALV', 'ALX', 'AM', 'AMAL',
    'AMAT', 'AMBA', 'AMBC', 'AMBO', 'AMBR', 'AMC', 'AMCR', 'AMCX',
    'AMD', 'AME', 'AMED', 'AMG', 'AMGN', 'AMH', 'AMKR', 'AMLP',
    'AMN', 'AMOM', 'AMP', 'AMPH', 'AMPY', 'AMR', 'AMRC', 'AMRK',
    'AMRN', 'AMRX', 'AMS', 'AMSC', 'AMSF', 'AMT', 'AMTB', 'AMUB',
    'AMWD', 'AMX', 'AMZA', 'AMZN', 'AN', 'ANAB', 'ANDE', 'ANET',
    'ANF', 'ANGI', 'ANGL', 'ANGO', 'ANIK', 'ANIP', 'ANIX', 'ANSS',
    'AOA', 'AOD', 'AOK', 'AOM', 'AON', 'AOR', 'AORT', 'AOS',
    'AOSL', 'APA', 'APAM', 'APD', 'APEI', 'APG', 'APH', 'APLD',
    'APLE', 'APLS', 'APO', 'APOG', 'APPF', 'APPN', 'APPS', 'APT',
    'APTV', 'AQN', 'AQST', 'AR', 'ARCB', 'ARCC', 'ARCM', 'ARCO',
    'ARCT', 'ARDC', 'ARDX', 'ARE', 'AREB', 'AREN', 'ARES', 'ARGT',
    'ARGX', 'ARI', 'ARKF', 'ARKG', 'ARKK', 'ARKO', 'ARKQ', 'ARKR',
    'ARKW', 'ARL', 'ARLO', 'ARLP', 'ARMK', 'ARMN', 'AROC', 'AROW',
    'ARQ', 'ARQT', 'ARR', 'ARTNA', 'ARTY', 'ARVN', 'ARW', 'ARWR',
    'ASA', 'ASB', 'ASC', 'ASEA', 'ASET', 'ASG', 'ASGN', 'ASH',
    'ASHR', 'ASHS', 'ASIX', 'ASLE', 'ASM', 'ASMB', 'ASML', 'ASND',
    'ASPN', 'ASR', 'ASRV', 'ASTC', 'ASTE', 'ASTH', 'ASTS', 'ASUR',
    'ASX', 'ASYS', 'ATEC', 'ATEN', 'ATEX', 'ATGE', 'ATHE', 'ATHM',
    'ATI', 'ATKR', 'ATLC', 'ATLO', 'ATLX', 'ATMP', 'ATNI', 'ATO',
    'ATOM', 'ATR', 'ATRA', 'ATRC', 'ATRO', 'ATS', 'ATUS', 'ATXS',
    'ATYR', 'AU', 'AUB', 'AUBN', 'AUDC', 'AUID', 'AUPH', 'AUSF',
    'AVA', 'AVAL', 'AVAV', 'AVB', 'AVD', 'AVDE', 'AVDL', 'AVDV',
    'AVEM', 'AVGO', 'AVK', 'AVNS', 'AVNT', 'AVNW', 'AVPT', 'AVT',
    'AVTR', 'AVTX', 'AVUS', 'AVUV', 'AVXL', 'AVY', 'AWAY', 'AWF',
    'AWI', 'AWK', 'AWP', 'AWR', 'AWX', 'AX', 'AXGN', 'AXIL',
    'AXL', 'AXON', 'AXP', 'AXR', 'AXS', 'AXSM', 'AXTA', 'AYI',
    'AZN', 'AZO', 'AZTA', 'AZZ', 'BA', 'BAB', 'BABA', 'BAC',
    'BAFN', 'BAH', 'BAK', 'BALL', 'BALY', 'BAM', 'BANC', 'BAND',
    'BANF', 'BANR', 'BANX', 'BAP', 'BAPR', 'BAR', 'BATRA', 'BATRK',
    'BATT', 'BAUG', 'BAX', 'BB', 'BBAG', 'BBAR', 'BBAX', 'BBC',
    'BBCA', 'BBCB', 'BBCP', 'BBD', 'BBDC', 'BBEU', 'BBGI', 'BBH',
    'BBHY', 'BBIN', 'BBIO', 'BBJP', 'BBMC', 'BBN', 'BBP', 'BBRE',
    'BBSI', 'BBU', 'BBUS', 'BBVA', 'BBW', 'BBWI', 'BBY', 'BC',
    'BCAL', 'BCBP', 'BCC', 'BCD', 'BCE', 'BCH', 'BCI', 'BCML',
    'BCO', 'BCPC', 'BCRX', 'BCS', 'BCSF', 'BCTX', 'BCV', 'BCX',
    'BCYC', 'BDC', 'BDCZ', 'BDEC', 'BDJ', 'BDL', 'BDN', 'BDRY',
    'BDX', 'BE', 'BEAM', 'BECN', 'BELFB', 'BEN', 'BEP', 'BERY',
    'BFAM', 'BFC', 'BFEB', 'BFH', 'BFIN', 'BFK', 'BFOR', 'BFS',
    'BFST', 'BFZ', 'BG', 'BGB', 'BGC', 'BGH', 'BGR', 'BGRN',
    'BGS', 'BGSF', 'BGT', 'BGX', 'BGY', 'BH', 'BHAT', 'BHB',
    'BHC', 'BHE', 'BHF', 'BHK', 'BHLB', 'BHP', 'BHRB', 'BHST',
    'BHV', 'BHVN', 'BIB', 'BIBL', 'BIDU', 'BIIB', 'BIL', 'BILI',
    'BILL', 'BIO', 'BIOX', 'BIP', 'BIPC', 'BIS', 'BIT', 'BIV',
    'BIZD', 'BJ', 'BJAN', 'BJK', 'BJRI', 'BJUL', 'BJUN', 'BK',
    'BKAG', 'BKD', 'BKE', 'BKEM', 'BKF', 'BKH', 'BKHY', 'BKIE',
    'BKLC', 'BKLN', 'BKMC', 'BKN', 'BKNG', 'BKR', 'BKSE', 'BKSY',
    'BKT', 'BKTI', 'BKU', 'BL', 'BLBD', 'BLBX', 'BLCN', 'BLD',
    'BLDE', 'BLDR', 'BLE', 'BLES', 'BLFS', 'BLK', 'BLKB', 'BLMN',
    'BLOK', 'BLRX', 'BLUE', 'BLV', 'BLW', 'BLX', 'BMA', 'BMAR',
    'BME', 'BMEZ', 'BMI', 'BMO', 'BMRA', 'BMRC', 'BMRN', 'BMVP',
    'BMY', 'BN', 'BND', 'BNDC', 'BNDW', 'BNDX', 'BNED', 'BNGO',
    'BNO', 'BNOV', 'BNS', 'BNTC', 'BNTX', 'BNY', 'BOC', 'BOCT',
    'BOE', 'BOH', 'BOIL', 'BOKF', 'BOND', 'BOOM', 'BOOT', 'BOSC',
    'BOTJ', 'BOTZ', 'BOUT', 'BOX', 'BP', 'BPMC', 'BPOP', 'BPRN',
    'BR', 'BRAG', 'BRBR', 'BRBS', 'BRC', 'BRF', 'BRFH', 'BRFS',
    'BRID', 'BRKL', 'BRKR', 'BRO', 'BRSP', 'BRT', 'BRW', 'BRX',
    'BRY', 'BRZU', 'BSAC', 'BSBK', 'BSBR', 'BSCP', 'BSCQ', 'BSCR',
    'BSCS', 'BSCT', 'BSEP', 'BSET', 'BSJP', 'BSJQ', 'BSJR', 'BSL',
    'BSM', 'BSMP', 'BSMQ', 'BSMR', 'BSMS', 'BSMT', 'BSRR', 'BST',
    'BSTZ', 'BSV', 'BSVN', 'BSX', 'BTA', 'BTAL', 'BTBT', 'BTCT',
    'BTG', 'BTI', 'BTO', 'BTT', 'BTTR', 'BTU', 'BTZ', 'BUD',
    'BUFF', 'BUG', 'BUI', 'BUL', 'BUR', 'BURL', 'BUSE', 'BUYZ',
    'BV', 'BVFL', 'BVN', 'BWA', 'BWAY', 'BWB', 'BWFG', 'BWG',
    'BWIN', 'BWLP', 'BWMX', 'BWX', 'BWXT', 'BWZ', 'BX', 'BXC',
    'BXMT', 'BXMX', 'BXP', 'BY', 'BYD', 'BYFC', 'BYLD', 'BYM',
    'BYND', 'BYON', 'BYRN', 'BZH', 'BZQ', 'BZUN', 'C', 'CAAP',
    'CAAS', 'CABO', 'CAC', 'CACC', 'CACI', 'CADE', 'CAE', 'CAF',
    'CAG', 'CAH', 'CAKE', 'CAL', 'CALF', 'CALM', 'CALX', 'CAMT',
    'CANE', 'CANG', 'CAPL', 'CAPR', 'CAPS', 'CAR', 'CARA', 'CARE',
    'CARG', 'CARR', 'CARS', 'CARZ', 'CASH', 'CASI', 'CASS', 'CASY',
    'CAT', 'CATH', 'CATO', 'CATX', 'CATY', 'CB', 'CBAN', 'CBFV',
    'CBNK', 'CBOE', 'CBON', 'CBRE', 'CBRL', 'CBSH', 'CBT', 'CBU',
    'CBZ', 'CC', 'CCAP', 'CCB', 'CCBG', 'CCD', 'CCEC', 'CCEL',
    'CCEP', 'CCI', 'CCIF', 'CCJ', 'CCK', 'CCL', 'CCM', 'CCNE',
    'CCOI', 'CCOR', 'CCRD', 'CCRN', 'CCS', 'CCU', 'CDC', 'CDE',
    'CDL', 'CDNA', 'CDNS', 'CDP', 'CDTX', 'CDW', 'CDXS', 'CDZI',
    'CE', 'CEAD', 'CECO', 'CEE', 'CEF', 'CEFS', 'CELC', 'CELH',
    'CEMB', 'CENT', 'CENTA', 'CENX', 'CEPU', 'CET', 'CEV', 'CEVA',
    'CEW', 'CF', 'CFA', 'CFBK', 'CFFI', 'CFFN', 'CFG', 'CFO',
    'CFR', 'CG', 'CGAU', 'CGBD', 'CGNX', 'CGO', 'CGW', 'CHAU',
    'CHCI', 'CHCO', 'CHCT', 'CHD', 'CHDN', 'CHE', 'CHEF', 'CHGX',
    'CHH', 'CHI', 'CHIQ', 'CHKP', 'CHMG', 'CHMI', 'CHN', 'CHRW',
    'CHT', 'CHTR', 'CHW', 'CHWY', 'CHX', 'CHY', 'CI', 'CIA',
    'CIB', 'CIBR', 'CIEN', 'CIGI', 'CII', 'CIIT', 'CIK', 'CIL',
    'CIM', 'CINF', 'CIO', 'CIVB', 'CIVI', 'CIX', 'CKPT', 'CKX',
    'CL', 'CLAR', 'CLB', 'CLBK', 'CLDT', 'CLDX', 'CLF', 'CLFD',
    'CLGN', 'CLH', 'CLIX', 'CLM', 'CLMB', 'CLMT', 'CLNN', 'CLOU',
    'CLPR', 'CLPT', 'CLS', 'CLSK', 'CLVT', 'CLW', 'CLX', 'CM',
    'CMA', 'CMBS', 'CMBT', 'CMC', 'CMCL', 'CMCM', 'CMCO', 'CMCSA',
    'CMCT', 'CMDY', 'CME', 'CMF', 'CMG', 'CMI', 'CMP', 'CMPR',
    'CMRE', 'CMRX', 'CMS', 'CMT', 'CMU', 'CNA', 'CNBS', 'CNC',
    'CNCR', 'CNDT', 'CNH', 'CNI', 'CNK', 'CNMD', 'CNNE', 'CNO',
    'CNOB', 'CNP', 'CNQ', 'CNR', 'CNRG', 'CNS', 'CNVS', 'CNX',
    'CNXN', 'CNXT', 'CNYA', 'CODA', 'CODI', 'COE', 'COF', 'COFS',
    'COGT', 'COHN', 'COHR', 'COHU', 'COKE', 'COLB', 'COLD', 'COLL',
    'COLM', 'COM', 'COMB', 'COMM', 'COMT', 'COO', 'COOP', 'COP',
    'COPX', 'COR', 'CORN', 'CORP', 'CORT', 'COST', 'COTY', 'COWZ',
    'CP', 'CPA', 'CPAC', 'CPAY', 'CPB', 'CPER', 'CPF', 'CPHC',
    'CPIX', 'CPK', 'CPRI', 'CPRT', 'CPRX', 'CPS', 'CPSS', 'CPT',
    'CPZ', 'CQP', 'CQQQ', 'CR', 'CRAI', 'CRAK', 'CRBN', 'CRBP',
    'CRDF', 'CRESY', 'CRF', 'CRH', 'CRI', 'CRK', 'CRL', 'CRM',
    'CRMD', 'CRMT', 'CRNC', 'CRNT', 'CRNX', 'CROX', 'CRS', 'CRSP',
    'CRT', 'CRTO', 'CRUS', 'CRVL', 'CRVO', 'CRVS', 'CRWD', 'CRWS',
    'CSA', 'CSB', 'CSBR', 'CSCI', 'CSCO', 'CSD', 'CSF', 'CSGP',
    'CSGS', 'CSIQ', 'CSL', 'CSM', 'CSPI', 'CSQ', 'CSR', 'CSTE',
    'CSTL', 'CSTM', 'CSV', 'CSWC', 'CSWI', 'CSX', 'CTAS', 'CTBI',
    'CTEV', 'CTGO', 'CTLP', 'CTO', 'CTOS', 'CTRA', 'CTRE', 'CTRM',
    'CTRN', 'CTS', 'CTSH', 'CTVA', 'CUBA', 'CUBE', 'CUBI', 'CUK',
    'CULP', 'CURE', 'CURI', 'CUT', 'CUZ', 'CVBF', 'CVCO', 'CVE',
    'CVEO', 'CVGW', 'CVI', 'CVLG', 'CVLT', 'CVNA', 'CVR', 'CVS',
    'CVU', 'CVV', 'CVX', 'CVY', 'CW', 'CWB', 'CWBC', 'CWCO',
    'CWEB', 'CWEN', 'CWH', 'CWI', 'CWK', 'CWS', 'CWST', 'CWT',
    'CX', 'CXDO', 'CXE', 'CXH', 'CXSE', 'CXT', 'CXW', 'CYBN',
    'CYBR', 'CYCN', 'CYD', 'CYH', 'CYRX', 'CYTK', 'CZA', 'CZFS',
    'CZNC', 'CZR', 'CZWI', 'D', 'DAC', 'DAIO', 'DAKT', 'DAL',
    'DALI', 'DALN', 'DAN', 'DAO', 'DAR', 'DARE', 'DAUG', 'DAVA',
    'DAX', 'DAY', 'DB', 'DBA', 'DBAW', 'DBB', 'DBC', 'DBE',
    'DBEF', 'DBEM', 'DBEU', 'DBEZ', 'DBI', 'DBJP', 'DBL', 'DBMF',
    'DBO', 'DBP', 'DBRG', 'DBVT', 'DBX', 'DCBO', 'DCI', 'DCO',
    'DCOM', 'DCTH', 'DD', 'DDIV', 'DDLS', 'DDM', 'DDOG', 'DDS',
    'DDWM', 'DE', 'DEA', 'DEC', 'DECK', 'DEEF', 'DEEP', 'DEI',
    'DELL', 'DEM', 'DENN', 'DEO', 'DES', 'DESP', 'DEUS', 'DEW',
    'DFE', 'DFEB', 'DFEN', 'DFIN', 'DFJ', 'DFND', 'DFNL', 'DFP',
    'DFS', 'DG', 'DGICA', 'DGII', 'DGP', 'DGRE', 'DGRO', 'DGRS',
    'DGRW', 'DGS', 'DGT', 'DGX', 'DGZ', 'DHC', 'DHF', 'DHI',
    'DHIL', 'DHR', 'DHS', 'DHT', 'DHY', 'DIA', 'DIAL', 'DIAX',
    'DIEM', 'DIG', 'DIM', 'DIN', 'DINO', 'DINT', 'DIOD', 'DIS',
    'DIT', 'DIV', 'DIVB', 'DIVI', 'DIVO', 'DJCO', 'DJD', 'DJP',
    'DK', 'DKL', 'DKNG', 'DKS', 'DLB', 'DLHC', 'DLN', 'DLNG',
    'DLR', 'DLS', 'DLTR', 'DLX', 'DLY', 'DMAC', 'DMB', 'DMF',
    'DMLP', 'DMO', 'DMRC', 'DNL', 'DNLI', 'DNOV', 'DNOW', 'DNP',
    'DNTH', 'DOC', 'DOCU', 'DOG', 'DOGZ', 'DOL', 'DOMH', 'DOMO',
    'DON', 'DOOO', 'DORM', 'DOV', 'DOW', 'DOX', 'DOYU', 'DPG',
    'DPRO', 'DPST', 'DPZ', 'DQ', 'DRD', 'DRH', 'DRI', 'DRIP',
    'DRIV', 'DRN', 'DRS', 'DRSK', 'DRUP', 'DRV', 'DSGR', 'DSGX',
    'DSI', 'DSL', 'DSM', 'DSTL', 'DSU', 'DSWL', 'DT', 'DTD',
    'DTE', 'DTEC', 'DTF', 'DTH', 'DTIL', 'DTRE', 'DTSS', 'DTST',
    'DUG', 'DUK', 'DUOT', 'DURA', 'DUSA', 'DUSL', 'DUST', 'DVA',
    'DVAX', 'DVLU', 'DVN', 'DVOL', 'DVY', 'DVYA', 'DVYE', 'DWAS',
    'DWAT', 'DWAW', 'DWCR', 'DWLD', 'DWM', 'DWMF', 'DWSH', 'DWUS',
    'DWX', 'DX', 'DXC', 'DXCM', 'DXD', 'DXF', 'DXJ', 'DXJS',
    'DXPE', 'DXR', 'DY', 'DYNF', 'E', 'EA', 'EAD', 'EAGG',
    'EARN', 'EASG', 'EAT', 'EB', 'EBAY', 'EBF', 'EBIZ', 'EBMT',
    'EBND', 'EBR', 'EBS', 'EBTC', 'EC', 'ECC', 'ECF', 'ECH',
    'ECL', 'ECLN', 'ECNS', 'ECO', 'ECON', 'ECOR', 'ECOW', 'ECPG',
    'ECVT', 'ED', 'EDAP', 'EDC', 'EDD', 'EDEN', 'EDF', 'EDIV',
    'EDN', 'EDOG', 'EDOW', 'EDRY', 'EDSA', 'EDU', 'EDV', 'EDZ',
    'EEA', 'EEFT', 'EELV', 'EEM', 'EEMA', 'EEMO', 'EEMS', 'EEMV',
    'EEMX', 'EES', 'EET', 'EEV', 'EEX', 'EFA', 'EFAD', 'EFAS',
    'EFAV', 'EFAX', 'EFC', 'EFG', 'EFNL', 'EFO', 'EFR', 'EFSC',
    'EFSI', 'EFT', 'EFU', 'EFV', 'EFX', 'EFXT', 'EFZ', 'EG',
    'EGAN', 'EGBN', 'EGO', 'EGP', 'EGY', 'EH', 'EHC', 'EHI',
    'EHTH', 'EIC', 'EIDO', 'EIG', 'EIM', 'EINC', 'EIRL', 'EIS',
    'EIX', 'EJAN', 'EJUL', 'EL', 'ELA', 'ELAN', 'ELD', 'ELDN',
    'ELF', 'ELLO', 'ELMD', 'ELME', 'ELP', 'ELS', 'ELSE', 'ELTK',
    'ELV', 'ELVA', 'ELVN', 'EMB', 'EMCB', 'EMCR', 'EMCS', 'EMD',
    'EMDV', 'EME', 'EMF', 'EMGF', 'EMHY', 'EMIF', 'EML', 'EMLC',
    'EMLP', 'EMMF', 'EMN', 'EMNT', 'EMO', 'EMQQ', 'EMR', 'EMTL',
    'EMTY', 'EMX', 'EMXC', 'ENB', 'ENFR', 'ENIC', 'ENOR', 'ENOV',
    'ENPH', 'ENR', 'ENS', 'ENSC', 'ENSG', 'ENTA', 'ENTG', 'ENTX',
    'ENVA', 'ENX', 'ENZL', 'EOD', 'EOG', 'EOI', 'EOLS', 'EOS',
    'EOT', 'EP', 'EPAC', 'EPAM', 'EPC', 'EPD', 'EPHE', 'EPI',
    'EPM', 'EPOL', 'EPP', 'EPR', 'EPRF', 'EPRT', 'EPS', 'EPSN',
    'EPU', 'EPV', 'EQAL', 'EQBK', 'EQH', 'EQIN', 'EQIX', 'EQL',
    'EQNR', 'EQR', 'EQRR', 'EQT', 'EQWL', 'EQX', 'ERC', 'ERH',
    'ERIC', 'ERIE', 'ERII', 'ERJ', 'ERO', 'ERTH', 'ERX', 'ERY',
    'ES', 'ESBA', 'ESCA', 'ESE', 'ESEA', 'ESG', 'ESGD', 'ESGE',
    'ESGG', 'ESGR', 'ESGU', 'ESGV', 'ESI', 'ESLT', 'ESML', 'ESNT',
    'ESOA', 'ESP', 'ESPO', 'ESQ', 'ESRT', 'ESS', 'ESSA', 'ESTA',
    'ESTC', 'ET', 'ETB', 'ETD', 'ETG', 'ETHE', 'ETHO', 'ETJ',
    'ETN', 'ETNB', 'ETO', 'ETON', 'ETR', 'ETSY', 'ETV', 'ETW',
    'ETX', 'ETY', 'EUDG', 'EUDV', 'EUFN', 'EUM', 'EUO', 'EURL',
    'EUSA', 'EUSC', 'EVBN', 'EVER', 'EVF', 'EVG', 'EVH', 'EVI',
    'EVM', 'EVN', 'EVO', 'EVOK', 'EVR', 'EVRG', 'EVRI', 'EVT',
    'EVTC', 'EVV', 'EVX', 'EW', 'EWA', 'EWBC', 'EWC', 'EWD',
    'EWG', 'EWH', 'EWI', 'EWJ', 'EWJV', 'EWK', 'EWL', 'EWM',
    'EWN', 'EWO', 'EWP', 'EWQ', 'EWS', 'EWT', 'EWU', 'EWUS',
    'EWV', 'EWW', 'EWX', 'EWY', 'EWZ', 'EWZS', 'EXAS', 'EXC',
    'EXEL', 'EXG', 'EXI', 'EXK', 'EXLS', 'EXP', 'EXPD', 'EXPE',
    'EXPI', 'EXPO', 'EXR', 'EXTR', 'EYE', 'EYLD', 'EYPT', 'EZA',
    'EZJ', 'EZM', 'EZPW', 'EZU', 'F', 'FAAR', 'FAB', 'FAD',
    'FAF', 'FALN', 'FAN', 'FANG', 'FARO', 'FAS', 'FAST', 'FAT',
    'FAUG', 'FAX', 'FAZ', 'FBIN', 'FBIZ', 'FBK', 'FBNC', 'FBND',
    'FBP', 'FBRX', 'FBT', 'FBZ', 'FC', 'FCA', 'FCAL', 'FCAP',
    'FCBC', 'FCCO', 'FCEF', 'FCEL', 'FCF', 'FCFS', 'FCG', 'FCN',
    'FCNCA', 'FCO', 'FCOM', 'FCOR', 'FCPI', 'FCPT', 'FCT', 'FCTR',
    'FCUV', 'FCVT', 'FCX', 'FDBC', 'FDD', 'FDEM', 'FDEV', 'FDG',
    'FDHY', 'FDIS', 'FDL', 'FDLO', 'FDM', 'FDMO', 'FDN', 'FDNI',
    'FDP', 'FDRR', 'FDS', 'FDT', 'FDTS', 'FDUS', 'FDVV', 'FDX',
    'FE', 'FEDU', 'FEIM', 'FELE', 'FEM', 'FEMB', 'FEMS', 'FENC',
    'FENY', 'FEP', 'FER', 'FERG', 'FET', 'FEUZ', 'FEX', 'FEZ',
    'FF', 'FFA', 'FFBC', 'FFC', 'FFEB', 'FFIC', 'FFIN', 'FFIU',
    'FFIV', 'FFNW', 'FFTY', 'FFWM', 'FGB', 'FGBI', 'FGD', 'FGF',
    'FGM', 'FHB', 'FHI', 'FHLC', 'FHN', 'FI', 'FIBK', 'FIBR',
    'FICO', 'FID', 'FIDI', 'FIDU', 'FILL', 'FINS', 'FINV', 'FINX',
    'FIS', 'FISI', 'FISR', 'FITB', 'FITE', 'FIVA', 'FIVE', 'FIVN',
    'FIW', 'FIX', 'FIXD', 'FIZZ', 'FJP', 'FKU', 'FKWL', 'FL',
    'FLAU', 'FLAX', 'FLBL', 'FLBR', 'FLC', 'FLCA', 'FLCB', 'FLCH',
    'FLCO', 'FLDR', 'FLEE', 'FLEU', 'FLEX', 'FLG', 'FLGB', 'FLGR',
    'FLGT', 'FLHK', 'FLHY', 'FLIA', 'FLIC', 'FLIN', 'FLJH', 'FLJP',
    'FLKR', 'FLL', 'FLLA', 'FLMB', 'FLMI', 'FLMX', 'FLN', 'FLNG',
    'FLNT', 'FLO', 'FLOT', 'FLQL', 'FLQM', 'FLQS', 'FLR', 'FLRN',
    'FLRT', 'FLS', 'FLSA', 'FLSP', 'FLSW', 'FLTB', 'FLTR', 'FLTW',
    'FLUT', 'FLV', 'FLWS', 'FLXS', 'FMAO', 'FMAT', 'FMB', 'FMBH',
    'FMC', 'FMF', 'FMHI', 'FMN', 'FMNB', 'FMS', 'FMX', 'FMY',
    'FN', 'FNB', 'FNCL', 'FND', 'FNDA', 'FNDB', 'FNDC', 'FNDE',
    'FNDF', 'FNDX', 'FNF', 'FNGA', 'FNGD', 'FNGO', 'FNGS', 'FNK',
    'FNKO', 'FNLC', 'FNOV', 'FNV', 'FNWB', 'FNWD', 'FNX', 'FNY',
    'FOA', 'FOF', 'FOLD', 'FONR', 'FOR', 'FORD', 'FORM', 'FORR',
    'FORTY', 'FOVL', 'FOX', 'FOXA', 'FOXF', 'FPA', 'FPE', 'FPEI',
    'FPF', 'FPH', 'FPI', 'FPX', 'FPXE', 'FPXI', 'FQAL', 'FR',
    'FRA', 'FRAF', 'FRBA', 'FRD', 'FRDM', 'FREL', 'FRHC', 'FRI',
    'FRME', 'FRO', 'FRPH', 'FRPT', 'FRST', 'FRT', 'FSBW', 'FSCS',
    'FSEA', 'FSFG', 'FSGS', 'FSI', 'FSK', 'FSLR', 'FSLY', 'FSM',
    'FSMB', 'FSMD', 'FSS', 'FSTA', 'FSTR', 'FSV', 'FSZ', 'FT',
    'FTA', 'FTAG', 'FTAI', 'FTC', 'FTCS', 'FTDR', 'FTDS', 'FTEC',
    'FTF', 'FTGC', 'FTHI', 'FTI', 'FTK', 'FTLF', 'FTLS', 'FTNT',
    'FTQI', 'FTRI', 'FTS', 'FTSD', 'FTSL', 'FTSM', 'FTV', 'FTXG',
    'FTXH', 'FTXL', 'FTXN', 'FTXO', 'FTXR', 'FUBO', 'FUL', 'FULC',
    'FULT', 'FUMB', 'FUN', 'FUNC', 'FUND', 'FUSB', 'FUTU', 'FUTY',
    'FV', 'FVAL', 'FVC', 'FVCB', 'FVD', 'FVRR', 'FWONA', 'FWONK',
    'FWRD', 'FXA', 'FXB', 'FXC', 'FXD', 'FXE', 'FXF', 'FXG',
    'FXH', 'FXI', 'FXL', 'FXN', 'FXNC', 'FXO', 'FXP', 'FXR',
    'FXU', 'FXY', 'FXZ', 'FYC', 'FYLD', 'FYT', 'FYX', 'G',
    'GAA', 'GAB', 'GABC', 'GAIA', 'GAIN', 'GAL', 'GAM', 'GAMR',
    'GAP', 'GARP', 'GASS', 'GATX', 'GB', 'GBAB', 'GBCI', 'GBDC',
    'GBF', 'GBIL', 'GBLI', 'GBX', 'GCBC', 'GCC', 'GCI', 'GCMG',
    'GCO', 'GCOW', 'GCV', 'GD', 'GDC', 'GDDY', 'GDEN', 'GDL',
    'GDMA', 'GDO', 'GDOT', 'GDS', 'GDV', 'GDX', 'GDXJ', 'GDYN',
    'GE', 'GECC', 'GEF', 'GEL', 'GEM', 'GEN', 'GENC', 'GEO',
    'GEOS', 'GES', 'GF', 'GFF', 'GFI', 'GFL', 'GGAL', 'GGB',
    'GGG', 'GGME', 'GGN', 'GGT', 'GGZ', 'GH', 'GHC', 'GHG',
    'GHI', 'GHM', 'GHY', 'GHYB', 'GHYG', 'GIB', 'GIC', 'GIFI',
    'GIGB', 'GII', 'GIII', 'GIL', 'GILD', 'GILT', 'GIS', 'GKOS',
    'GL', 'GLAD', 'GLBZ', 'GLD', 'GLDD', 'GLDI', 'GLDM', 'GLIN',
    'GLL', 'GLNG', 'GLO', 'GLOB', 'GLOF', 'GLP', 'GLPG', 'GLPI',
    'GLQ', 'GLRE', 'GLTR', 'GLU', 'GLV', 'GLW', 'GM', 'GMAB',
    'GME', 'GMED', 'GMF', 'GMGI', 'GMOM', 'GMRE', 'GMS', 'GNE',
    'GNFT', 'GNK', 'GNL', 'GNMA', 'GNOM', 'GNR', 'GNRC', 'GNSS',
    'GNT', 'GNTX', 'GNTY', 'GNW', 'GO', 'GOAU', 'GOEX', 'GOF',
    'GOGL', 'GOGO', 'GOLD', 'GOLF', 'GOOD', 'GOOG', 'GOOGL', 'GOOS',
    'GOTU', 'GOVI', 'GOVT', 'GPC', 'GPI', 'GPK', 'GPN', 'GPRE',
    'GPRK', 'GQRE', 'GRBK', 'GRC', 'GRCE', 'GREK', 'GRF', 'GRFS',
    'GRID', 'GRMN', 'GRN', 'GRNB', 'GROW', 'GRPM', 'GRPN', 'GRVY',
    'GRX', 'GS', 'GSAT', 'GSBC', 'GSBD', 'GSEU', 'GSEW', 'GSG',
    'GSHD', 'GSIE', 'GSIT', 'GSJY', 'GSK', 'GSL', 'GSLC', 'GSM',
    'GSSC', 'GSST', 'GSY', 'GT', 'GTBP', 'GTE', 'GTES', 'GTIP',
    'GTLS', 'GTN', 'GTO', 'GTX', 'GTY', 'GUNR', 'GURU', 'GUSH',
    'GUT', 'GVA', 'GVAL', 'GVI', 'GVIP', 'GWRE', 'GWRS', 'GWW',
    'GWX', 'GXC', 'GXDW', 'GXG', 'GYLD', 'GYRE', 'GYRO', 'H',
    'HACK', 'HAE', 'HAFC', 'HAIL', 'HAIN', 'HAL', 'HALO', 'HAP',
    'HAS', 'HASI', 'HAUZ', 'HAWX', 'HBAN', 'HBB', 'HBCP', 'HBI',
    'HBM', 'HBNC', 'HBT', 'HCA', 'HCAT', 'HCC', 'HCI', 'HCKT',
    'HCM', 'HCRB', 'HCSG', 'HD', 'HDB', 'HDEF', 'HDG', 'HDGE',
    'HDLB', 'HDMV', 'HDSN', 'HDV', 'HE', 'HEDJ', 'HEEM', 'HEES',
    'HEFA', 'HEI', 'HELE', 'HELX', 'HEQ', 'HERD', 'HERO', 'HES',
    'HESM', 'HEWJ', 'HEZU', 'HFBL', 'HFFG', 'HFRO', 'HFWA', 'HFXI',
    'HGBL', 'HGLB', 'HGV', 'HHH', 'HHS', 'HI', 'HIBL', 'HIBS',
    'HIFS', 'HIG', 'HII', 'HIMS', 'HIMX', 'HIO', 'HIPS', 'HISF',
    'HITI', 'HIW', 'HIX', 'HL', 'HLAL', 'HLF', 'HLI', 'HLIO',
    'HLIT', 'HLNE', 'HLT', 'HLX', 'HMC', 'HMN', 'HMOP', 'HMST',
    'HMY', 'HNDL', 'HNI', 'HNNA', 'HNRG', 'HNW', 'HOFT', 'HOG',
    'HOLX', 'HOMB', 'HOMZ', 'HON', 'HONE', 'HOPE', 'HOUS', 'HOV',
    'HP', 'HPE', 'HPF', 'HPH', 'HPI', 'HPK', 'HPP', 'HPQ',
    'HPS', 'HQH', 'HQI', 'HQL', 'HQY', 'HR', 'HRB', 'HRI',
    'HRL', 'HROW', 'HRTG', 'HRTX', 'HRZN', 'HSBC', 'HSCZ', 'HSIC',
    'HSII', 'HSMV', 'HSON', 'HST', 'HSTM', 'HSY', 'HTAB', 'HTB',
    'HTBK', 'HTD', 'HTEC', 'HTGC', 'HTH', 'HTHT', 'HTLD', 'HTRB',
    'HTUS', 'HUBB', 'HUBG', 'HUBS', 'HUM', 'HUN', 'HURA', 'HURC',
    'HURN', 'HUSV', 'HUT', 'HUYA', 'HVT', 'HWBK', 'HWC', 'HWKN',
    'HWM', 'HXL', 'HY', 'HYD', 'HYDB', 'HYDW', 'HYEM', 'HYG',
    'HYGH', 'HYGV', 'HYHG', 'HYI', 'HYLB', 'HYLS', 'HYMB', 'HYMC',
    'HYS', 'HYSA', 'HYT', 'HYTR', 'HYUP', 'HYXF', 'HYXU', 'HYZD',
    'HZO', 'IAC', 'IAE', 'IAF', 'IAG', 'IAGG', 'IAI', 'IAK',
    'IART', 'IAT', 'IAU', 'IBB', 'IBCP', 'IBD', 'IBDQ', 'IBDR',
    'IBDS', 'IBDT', 'IBDU', 'IBHE', 'IBKR', 'IBM', 'IBMN', 'IBMO',
    'IBMP', 'IBMQ', 'IBN', 'IBND', 'IBOC', 'IBP', 'IBRX', 'IBTF',
    'IBTG', 'IBTH', 'IBTI', 'IBTJ', 'IBUY', 'ICAD', 'ICCC', 'ICE',
    'ICF', 'ICFI', 'ICHR', 'ICL', 'ICLN', 'ICLR', 'ICMB', 'ICOW',
    'ICSH', 'ICUI', 'ICVT', 'IDA', 'IDCC', 'IDE', 'IDEV', 'IDGT',
    'IDHQ', 'IDLV', 'IDMO', 'IDN', 'IDNA', 'IDOG', 'IDR', 'IDRV',
    'IDT', 'IDU', 'IDV', 'IDX', 'IDXX', 'IDYA', 'IEDI', 'IEF',
    'IEFA', 'IEI', 'IEMG', 'IEO', 'IEP', 'IESC', 'IETC', 'IEUR',
    'IEUS', 'IEV', 'IEX', 'IEZ', 'IFF', 'IFGL', 'IFN', 'IFRA',
    'IFS', 'IFV', 'IG', 'IGA', 'IGBH', 'IGD', 'IGE', 'IGEB',
    'IGF', 'IGHG', 'IGI', 'IGIB', 'IGIC', 'IGLB', 'IGM', 'IGOV',
    'IGPT', 'IGR', 'IGRO', 'IGSB', 'IGT', 'IGV', 'IHAK', 'IHD',
    'IHDG', 'IHE', 'IHF', 'IHG', 'IHI', 'IHT', 'IHY', 'IIF',
    'IIGD', 'III', 'IIIN', 'IIIV', 'IIM', 'IIPR', 'IJAN', 'IJH',
    'IJJ', 'IJK', 'IJR', 'IJS', 'IJT', 'IJUL', 'ILCB', 'ILCG',
    'ILCV', 'ILF', 'ILMN', 'ILPT', 'ILTB', 'IMAX', 'IMCB', 'IMCG',
    'IMCV', 'IMKTA', 'IMMR', 'IMO', 'IMOM', 'IMOS', 'IMTB', 'IMTM',
    'IMTX', 'IMVT', 'IMXI', 'INBK', 'INCE', 'INCO', 'INCY', 'INDA',
    'INDB', 'INDI', 'INDL', 'INDO', 'INDS', 'INDV', 'INDY', 'INEQ',
    'INFU', 'INFY', 'ING', 'INGN', 'INGR', 'INKM', 'INLX', 'INM',
    'INMB', 'INMD', 'INN', 'INOD', 'INSE', 'INSG', 'INSM', 'INSP',
    'INSW', 'INTC', 'INTF', 'INTG', 'INTT', 'INTU', 'INVA', 'INVE',
    'INVH', 'INVX', 'IONS', 'IOO', 'IOR', 'IOSP', 'IOVA', 'IP',
    'IPAC', 'IPAR', 'IPAY', 'IPG', 'IPGP', 'IPI', 'IPKW', 'IPO',
    'IPOS', 'IPWR', 'IQDF', 'IQDG', 'IQDY', 'IQI', 'IQLT', 'IQM',
    'IQSI', 'IQSU', 'IQV', 'IR', 'IRBT', 'IRDM', 'IRM', 'IRMD',
    'IROQ', 'IRS', 'IRT', 'IRTC', 'ISCB', 'ISCF', 'ISCG', 'ISCV',
    'ISD', 'ISHG', 'ISHP', 'ISMD', 'ISRA', 'ISRG', 'ISSC', 'ISTB',
    'ISTR', 'IT', 'ITA', 'ITB', 'ITEQ', 'ITGR', 'ITIC', 'ITM',
    'ITOT', 'ITRI', 'ITRN', 'ITT', 'ITUB', 'ITW', 'IUS', 'IUSB',
    'IUSG', 'IUSV', 'IVAL', 'IVDA', 'IVE', 'IVLU', 'IVOG', 'IVOL',
    'IVOO', 'IVOV', 'IVR', 'IVT', 'IVV', 'IVW', 'IVZ', 'IWB',
    'IWC', 'IWD', 'IWF', 'IWL', 'IWM', 'IWN', 'IWO', 'IWP',
    'IWR', 'IWS', 'IWV', 'IWX', 'IWY', 'IX', 'IXC', 'IXG',
    'IXJ', 'IXN', 'IXP', 'IXUS', 'IYC', 'IYE', 'IYF', 'IYG',
    'IYH', 'IYJ', 'IYK', 'IYLD', 'IYM', 'IYR', 'IYT', 'IYW',
    'IYY', 'IYZ', 'IZRL', 'J', 'JACK', 'JAGX', 'JAKK', 'JAZZ',
    'JBGS', 'JBHT', 'JBI', 'JBL', 'JBLU', 'JBSS', 'JBTM', 'JCE',
    'JCI', 'JCPB', 'JCTC', 'JD', 'JDST', 'JEF', 'JELD', 'JEQ',
    'JETS', 'JFIN', 'JFR', 'JG', 'JGH', 'JHEM', 'JHG', 'JHI',
    'JHMD', 'JHML', 'JHMM', 'JHS', 'JHSC', 'JHX', 'JILL', 'JJSF',
    'JKHY', 'JKS', 'JLL', 'JLS', 'JMBS', 'JMIA', 'JMM', 'JMOM',
    'JMSB', 'JMST', 'JMUB', 'JNJ', 'JNK', 'JNPR', 'JNUG', 'JOE',
    'JOF', 'JOUT', 'JOYY', 'JPC', 'JPEM', 'JPI', 'JPIB', 'JPIN',
    'JPM', 'JPMB', 'JPME', 'JPSE', 'JPST', 'JPUS', 'JPXN', 'JQC',
    'JQUA', 'JRI', 'JRS', 'JRSH', 'JRVR', 'JSMD', 'JSML', 'JSPR',
    'JUST', 'JVA', 'JVAL', 'JWN', 'JXG', 'JXI', 'JYNT', 'K',
    'KAI', 'KALA', 'KALL', 'KALU', 'KALV', 'KAPR', 'KAR', 'KARS',
    'KB', 'KBA', 'KBE', 'KBH', 'KBR', 'KBWB', 'KBWD', 'KBWP',
    'KBWR', 'KBWY', 'KCE', 'KDP', 'KE', 'KELYA', 'KEMQ', 'KEMX',
    'KEN', 'KEP', 'KEQU', 'KEX', 'KEY', 'KEYS', 'KF', 'KFFB',
    'KFRC', 'KFS', 'KFY', 'KGC', 'KGEI', 'KGRN', 'KHC', 'KHYB',
    'KIDS', 'KIE', 'KIM', 'KINS', 'KIO', 'KJAN', 'KKR', 'KLAC',
    'KLIC', 'KLXE', 'KMB', 'KMDA', 'KMI', 'KMPR', 'KMT', 'KMX',
    'KN', 'KNCT', 'KNG', 'KNGZ', 'KNO', 'KNOP', 'KNSA', 'KNSL',
    'KNTK', 'KNX', 'KO', 'KOCT', 'KOD', 'KODK', 'KOF', 'KOKU',
    'KOLD', 'KOMP', 'KOP', 'KORP', 'KORU', 'KOSS', 'KPLT', 'KPRX',
    'KPTI', 'KR', 'KRC', 'KRE', 'KREF', 'KRG', 'KRKR', 'KRMA',
    'KRMD', 'KRNT', 'KRNY', 'KRO', 'KROS', 'KRP', 'KRRO', 'KRUS',
    'KRYS', 'KSA', 'KSS', 'KT', 'KTB', 'KTCC', 'KTF', 'KTOS',
    'KURA', 'KURE', 'KVHI', 'KW', 'KWEB', 'KWR', 'KXI', 'KYN',
    'KZIA', 'KZR', 'L', 'LABD', 'LABU', 'LAC', 'LAD', 'LADR',
    'LAKE', 'LAMR', 'LANC', 'LAND', 'LAR', 'LARK', 'LASR', 'LAUR',
    'LAZ', 'LAZR', 'LBRDA', 'LBRDK', 'LBRT', 'LBTYA', 'LBTYK', 'LC',
    'LCII', 'LCNB', 'LCR', 'LCUT', 'LDEM', 'LDOS', 'LDP', 'LDSF',
    'LDUR', 'LDWY', 'LE', 'LEA', 'LEAD', 'LECO', 'LEDS', 'LEE',
    'LEG', 'LEGH', 'LEGR', 'LEMB', 'LEN', 'LEO', 'LEU', 'LEVI',
    'LFCR', 'LFEQ', 'LFMD', 'LFT', 'LFUS', 'LFVN', 'LGH', 'LGHL',
    'LGI', 'LGIH', 'LGL', 'LGLV', 'LGND', 'LGOV', 'LH', 'LHX',
    'LII', 'LILA', 'LILAK', 'LIN', 'LINC', 'LIND', 'LINK', 'LIT',
    'LITE', 'LIVE', 'LIVN', 'LKFN', 'LKOR', 'LKQ', 'LLY', 'LMAT',
    'LMB', 'LMBS', 'LMNR', 'LMT', 'LNC', 'LND', 'LNG', 'LNN',
    'LNT', 'LNTH', 'LNW', 'LOAN', 'LOB', 'LOCO', 'LODE', 'LOGI',
    'LOMA', 'LOPE', 'LOUP', 'LOVE', 'LOW', 'LPCN', 'LPG', 'LPL',
    'LPLA', 'LPTH', 'LPX', 'LQD', 'LQDA', 'LQDH', 'LQDI', 'LQDT',
    'LRCX', 'LRFC', 'LRGE', 'LRGF', 'LRMR', 'LRN', 'LRNZ', 'LSAF',
    'LSAK', 'LSBK', 'LSCC', 'LSEA', 'LSPD', 'LSTA', 'LSTR', 'LTBR',
    'LTC', 'LTL', 'LTM', 'LTPZ', 'LTRX', 'LULU', 'LUMN', 'LUV',
    'LVHD', 'LVHI', 'LVS', 'LW', 'LWAY', 'LX', 'LXFR', 'LXP',
    'LXU', 'LYB', 'LYFT', 'LYG', 'LYTS', 'LYV', 'LZB', 'M',
    'MA', 'MAA', 'MAC', 'MAG', 'MAGA', 'MAGN', 'MAIN', 'MAMA',
    'MAN', 'MANH', 'MANU', 'MAR', 'MARA', 'MARB', 'MARPS', 'MAS',
    'MASI', 'MAT', 'MATV', 'MATW', 'MATX', 'MAV', 'MAYS', 'MBB',
    'MBCN', 'MBI', 'MBIN', 'MBNKP', 'MBOT', 'MBSD', 'MBUU', 'MBWM',
    'MC', 'MCB', 'MCBS', 'MCD', 'MCFT', 'MCHI', 'MCHP', 'MCI',
    'MCK', 'MCN', 'MCO', 'MCR', 'MCRB', 'MCRI', 'MCS', 'MCY',
    'MD', 'MDB', 'MDGL', 'MDIV', 'MDLZ', 'MDRR', 'MDT', 'MDU',
    'MDWD', 'MDXG', 'MDY', 'MDYG', 'MDYV', 'MEAR', 'MEC', 'MED',
    'MEDP', 'MEI', 'MEIP', 'MELI', 'MEOH', 'MERC', 'MESO', 'MET',
    'META', 'METC', 'MEXX', 'MFA', 'MFC', 'MFDX', 'MFEM', 'MFG',
    'MFH', 'MFIC', 'MFIN', 'MFLX', 'MFM', 'MFUS', 'MG', 'MGA',
    'MGC', 'MGEE', 'MGF', 'MGIC', 'MGK', 'MGM', 'MGNI', 'MGPI',
    'MGRC', 'MGTX', 'MGV', 'MGY', 'MGYR', 'MHD', 'MHF', 'MHH',
    'MHI', 'MHK', 'MHN', 'MHO', 'MI', 'MIDD', 'MIDU', 'MILN',
    'MIN', 'MIND', 'MINT', 'MIRM', 'MITK', 'MITT', 'MIY', 'MJ',
    'MKC', 'MKL', 'MKSI', 'MKTX', 'MLAB', 'MLCO', 'MLI', 'MLKN',
    'MLM', 'MLN', 'MLP', 'MLPA', 'MLPB', 'MLPX', 'MLR', 'MMC',
    'MMD', 'MMI', 'MMIN', 'MMIT', 'MMLP', 'MMM', 'MMS', 'MMSI',
    'MMT', 'MMTM', 'MMU', 'MMYT', 'MNA', 'MNKD', 'MNMD', 'MNPR',
    'MNRO', 'MNSB', 'MNST', 'MO', 'MOAT', 'MOD', 'MODG', 'MOFG',
    'MOGU', 'MOH', 'MOMO', 'MOO', 'MORN', 'MORT', 'MOS', 'MOTG',
    'MOTI', 'MOTO', 'MOV', 'MPA', 'MPAA', 'MPB', 'MPC', 'MPLX',
    'MPV', 'MPW', 'MPWR', 'MPX', 'MQT', 'MQY', 'MRAM', 'MRBK',
    'MRC', 'MRCC', 'MRCY', 'MREO', 'MRGR', 'MRK', 'MRNA', 'MRTN',
    'MRUS', 'MRVL', 'MS', 'MSA', 'MSB', 'MSBI', 'MSC', 'MSCI',
    'MSD', 'MSEX', 'MSFT', 'MSGE', 'MSGS', 'MSI', 'MSM', 'MSTR',
    'MT', 'MTA', 'MTB', 'MTCH', 'MTD', 'MTDR', 'MTEX', 'MTG',
    'MTGP', 'MTH', 'MTLS', 'MTN', 'MTR', 'MTRN', 'MTRX', 'MTSI',
    'MTUM', 'MTUS', 'MTW', 'MTX', 'MTZ', 'MU', 'MUA', 'MUB',
    'MUC', 'MUE', 'MUFG', 'MUJ', 'MUNI', 'MUR', 'MUSA', 'MUST',
    'MUX', 'MVBF', 'MVF', 'MVO', 'MVST', 'MVT', 'MVV', 'MWA',
    'MX', 'MXC', 'MXCT', 'MXE', 'MXF', 'MXI', 'MXL', 'MYD',
    'MYE', 'MYFW', 'MYGN', 'MYI', 'MYN', 'MYO', 'MYRG', 'MYY',
    'MZZ', 'NAC', 'NACP', 'NAD', 'NAGE', 'NAII', 'NAIL', 'NAN',
    'NANR', 'NAOV', 'NAPR', 'NAT', 'NATH', 'NATR', 'NAVI', 'NAYA',
    'NAZ', 'NB', 'NBB', 'NBH', 'NBHC', 'NBIS', 'NBIX', 'NBN',
    'NBR', 'NBTB', 'NC', 'NCA', 'NCLH', 'NCMI', 'NCSM', 'NCTY',
    'NCV', 'NCZ', 'NDAQ', 'NDRA', 'NDSN', 'NEA', 'NEAR', 'NECB',
    'NEE', 'NEGG', 'NEM', 'NEN', 'NEO', 'NEOG', 'NEON', 'NEPH',
    'NERD', 'NESR', 'NET', 'NETL', 'NEU', 'NEWT', 'NEXA', 'NEXT',
    'NFBK', 'NFE', 'NFG', 'NFJ', 'NFLT', 'NFLX', 'NFRA', 'NFTY',
    'NG', 'NGD', 'NGG', 'NGL', 'NGNE', 'NGS', 'NGVC', 'NGVT',
    'NHC', 'NHI', 'NHS', 'NHTC', 'NI', 'NIC', 'NICE', 'NIE',
    'NIM', 'NIO', 'NISN', 'NIU', 'NJAN', 'NJR', 'NKE', 'NKSH',
    'NKX', 'NL', 'NLR', 'NLY', 'NMCO', 'NMFC', 'NMI', 'NMIH',
    'NML', 'NMM', 'NMR', 'NMRK', 'NMS', 'NMT', 'NMZ', 'NNI',
    'NNN', 'NNY', 'NOA', 'NOAH', 'NOBL', 'NOC', 'NOCT', 'NODK',
    'NOG', 'NOK', 'NOM', 'NOMD', 'NORW', 'NOV', 'NOVT', 'NOW',
    'NPK', 'NPKI', 'NPO', 'NPV', 'NQP', 'NRC', 'NREF', 'NRG',
    'NRIM', 'NRK', 'NRO', 'NRP', 'NRT', 'NRXP', 'NSA', 'NSC',
    'NSIT', 'NSP', 'NSPR', 'NSSC', 'NSYS', 'NTAP', 'NTB', 'NTCT',
    'NTES', 'NTGR', 'NTIC', 'NTLA', 'NTNX', 'NTR', 'NTRA', 'NTRB',
    'NTRP', 'NTRS', 'NTSX', 'NTWK', 'NTZ', 'NUAG', 'NUBD', 'NUDM',
    'NUE', 'NUEM', 'NUGT', 'NUHY', 'NULC', 'NULG', 'NULV', 'NUMG',
    'NUMV', 'NURE', 'NURO', 'NUS', 'NUSA', 'NUSC', 'NUTX', 'NUV',
    'NUW', 'NVAX', 'NVCR', 'NVDA', 'NVEC', 'NVEE', 'NVG', 'NVGS',
    'NVMI', 'NVNO', 'NVO', 'NVR', 'NVRI', 'NVS', 'NVST', 'NVT',
    'NWBI', 'NWE', 'NWFL', 'NWG', 'NWL', 'NWN', 'NWPX', 'NWS',
    'NWSA', 'NX', 'NXC', 'NXDT', 'NXE', 'NXG', 'NXJ', 'NXN',
    'NXP', 'NXPI', 'NXRT', 'NXST', 'NXTG', 'NYF', 'NYMT', 'NYT',
    'NZAC', 'NZF', 'O', 'OBDC', 'OBE', 'OBK', 'OBLG', 'OBOR',
    'OBT', 'OC', 'OCC', 'OCCI', 'OCFC', 'OCFT', 'OCIO', 'OCSL',
    'OCUL', 'OCX', 'ODC', 'ODFL', 'ODP', 'OEC', 'OEF', 'OEUR',
    'OFG', 'OFIX', 'OFLX', 'OFS', 'OGE', 'OGIG', 'OGS', 'OHI',
    'OI', 'OIA', 'OIH', 'OII', 'OILK', 'OIS', 'OKE', 'OKTA',
    'OLED', 'OLLI', 'OLN', 'OLP', 'OMAB', 'OMC', 'OMCC', 'OMCL',
    'OMER', 'OMF', 'OMFL', 'OMFS', 'OMI', 'ON', 'ONB', 'ONC',
    'ONEO', 'ONEQ', 'ONEV', 'ONEW', 'ONEY', 'ONIT', 'ONLN', 'ONTO',
    'OOMA', 'OPBK', 'OPCH', 'OPER', 'OPHC', 'OPOF', 'OPP', 'OPRA',
    'OPRT', 'OPRX', 'OPTN', 'OPXS', 'OPY', 'OR', 'ORA', 'ORC',
    'ORCL', 'ORGO', 'ORI', 'ORIC', 'ORKA', 'ORLA', 'ORLY', 'ORMP',
    'ORN', 'ORRF', 'OSBC', 'OSCV', 'OSIS', 'OSK', 'OSPN', 'OSS',
    'OSUR', 'OSW', 'OTEX', 'OTIS', 'OTTR', 'OUNZ', 'OUSA', 'OUSM',
    'OUT', 'OVB', 'OVBC', 'OVF', 'OVL', 'OVLY', 'OVM', 'OVS',
    'OVV', 'OXLC', 'OXM', 'OXSQ', 'OXY', 'OZK', 'PAA', 'PAAS',
    'PAC', 'PACK', 'PAG', 'PAGP', 'PAGS', 'PAHC', 'PAI', 'PALL',
    'PAM', 'PAMT', 'PANL', 'PANW', 'PAPR', 'PAR', 'PARA', 'PARR',
    'PATK', 'PAUG', 'PAVE', 'PAWZ', 'PAYC', 'PAYS', 'PAYX', 'PB',
    'PBA', 'PBD', 'PBE', 'PBF', 'PBFS', 'PBH', 'PBHC', 'PBI',
    'PBJ', 'PBP', 'PBPB', 'PBR', 'PBT', 'PBTP', 'PBUS', 'PBW',
    'PBYI', 'PCAR', 'PCB', 'PCEF', 'PCF', 'PCG', 'PCH', 'PCK',
    'PCM', 'PCN', 'PCQ', 'PCRX', 'PCTY', 'PCY', 'PCYO', 'PD',
    'PDBC', 'PDCO', 'PDD', 'PDEC', 'PDEX', 'PDFS', 'PDI', 'PDLB',
    'PDM', 'PDN', 'PDP', 'PDS', 'PDT', 'PDX', 'PEB', 'PEBK',
    'PEBO', 'PEG', 'PEGA', 'PEJ', 'PEN', 'PENG', 'PENN', 'PEO',
    'PEP', 'PERI', 'PESI', 'PETS', 'PEX', 'PEXL', 'PEY', 'PEZ',
    'PFBC', 'PFD', 'PFE', 'PFEB', 'PFF', 'PFFA', 'PFFD', 'PFFL',
    'PFFR', 'PFG', 'PFGC', 'PFI', 'PFIG', 'PFIS', 'PFL', 'PFLD',
    'PFLT', 'PFM', 'PFN', 'PFO', 'PFS', 'PFSI', 'PFX', 'PFXF',
    'PG', 'PGC', 'PGF', 'PGHY', 'PGJ', 'PGNY', 'PGP', 'PGR',
    'PGRE', 'PGX', 'PGZ', 'PH', 'PHAT', 'PHB', 'PHD', 'PHDG',
    'PHG', 'PHI', 'PHIO', 'PHK', 'PHLT', 'PHM', 'PHO', 'PHR',
    'PHT', 'PHUN', 'PHX', 'PHYL', 'PHYS', 'PI', 'PICB', 'PICK',
    'PID', 'PIE', 'PII', 'PILL', 'PIM', 'PIN', 'PINC', 'PINE',
    'PINS', 'PIO', 'PIPR', 'PIZ', 'PJAN', 'PJP', 'PJT', 'PJUL',
    'PJUN', 'PK', 'PKB', 'PKBK', 'PKE', 'PKG', 'PKOH', 'PKW',
    'PKX', 'PLAB', 'PLAY', 'PLBC', 'PLCE', 'PLD', 'PLL', 'PLMR',
    'PLNT', 'PLOW', 'PLPC', 'PLSE', 'PLTM', 'PLUR', 'PLUS', 'PLX',
    'PLXS', 'PLYA', 'PLYM', 'PM', 'PMAR', 'PMF', 'PML', 'PMM',
    'PMO', 'PMT', 'PMTS', 'PMX', 'PNBK', 'PNC', 'PNF', 'PNFP',
    'PNI', 'PNNT', 'PNOV', 'PNQI', 'PNR', 'PNRG', 'PNTG', 'PNW',
    'POCI', 'POCT', 'PODD', 'POET', 'POLA', 'POOL', 'POR', 'POST',
    'POWA', 'POWI', 'POWL', 'PPA', 'PPBI', 'PPBT', 'PPC', 'PPG',
    'PPH', 'PPIH', 'PPL', 'PPLT', 'PPSI', 'PPT', 'PPTA', 'PPTY',
    'PR', 'PRA', 'PRAA', 'PRCH', 'PRDO', 'PREF', 'PRF', 'PRFZ',
    'PRG', 'PRGO', 'PRGS', 'PRI', 'PRIM', 'PRK', 'PRKS', 'PRLB',
    'PRMB', 'PRN', 'PRNT', 'PRO', 'PROF', 'PROP', 'PROV', 'PRPO',
    'PRSU', 'PRT', 'PRTA', 'PRTG', 'PRTH', 'PRU', 'PSA', 'PSC',
    'PSCC', 'PSCD', 'PSCE', 'PSCF', 'PSCH', 'PSCI', 'PSCM', 'PSCT',
    'PSCU', 'PSEC', 'PSEP', 'PSET', 'PSF', 'PSI', 'PSIX', 'PSK',
    'PSL', 'PSLV', 'PSMT', 'PSN', 'PSNL', 'PSO', 'PSP', 'PSQ',
    'PSR', 'PST', 'PSTG', 'PSTL', 'PSX', 'PTBD', 'PTC', 'PTCT',
    'PTEN', 'PTEU', 'PTF', 'PTGX', 'PTH', 'PTIN', 'PTLC', 'PTMC',
    'PTMN', 'PTNQ', 'PTON', 'PTY', 'PUI', 'PUK', 'PULM', 'PULS',
    'PUMP', 'PVBC', 'PVH', 'PVI', 'PVLA', 'PWB', 'PWOD', 'PWR',
    'PWS', 'PWV', 'PWZ', 'PXE', 'PXF', 'PXH', 'PXI', 'PXJ',
    'PXS', 'PY', 'PYN', 'PYPL', 'PYZ', 'PZA', 'PZC', 'PZT',
    'PZZA', 'QABA', 'QAI', 'QARP', 'QAT', 'QCLN', 'QCOM', 'QCRH',
    'QD', 'QDEF', 'QDEL', 'QDF', 'QDIV', 'QEFA', 'QEMM', 'QFIN',
    'QGEN', 'QGRO', 'QHY', 'QID', 'QIG', 'QINT', 'QIPT', 'QLC',
    'QLD', 'QLGN', 'QLTA', 'QLV', 'QLVD', 'QLVE', 'QLYS', 'QMCO',
    'QMOM', 'QNRX', 'QNST', 'QNTM', 'QQEW', 'QQH', 'QQQ', 'QQQE',
    'QQQH', 'QQQX', 'QQXT', 'QRFT', 'QRHC', 'QRVO', 'QSIG', 'QSR',
    'QTEC', 'QTRX', 'QTUM', 'QTWO', 'QUAD', 'QUAL', 'QUBT', 'QUIK',
    'QURE', 'QUS', 'QVAL', 'QWLD', 'QXO', 'QYLD', 'R', 'RA',
    'RAAX', 'RACE', 'RAFE', 'RAIL', 'RAMP', 'RAND', 'RARE', 'RAVE',
    'RAVI', 'RBA', 'RBB', 'RBBN', 'RBC', 'RBCAA', 'RBKB', 'RBLD',
    'RC', 'RCAT', 'RCEL', 'RCG', 'RCI', 'RCKT', 'RCKY', 'RCL',
    'RCMT', 'RCS', 'RCUS', 'RDCM', 'RDFN', 'RDHL', 'RDIV', 'RDN',
    'RDNT', 'RDOG', 'RDUS', 'RDVT', 'RDVY', 'RDWR', 'RDY', 'REAL',
    'RECS', 'REET', 'REG', 'REGL', 'REGN', 'REK', 'RELL', 'RELX',
    'REM', 'REMX', 'REPL', 'REPX', 'RES', 'RETL', 'RETO', 'REVG',
    'REVS', 'REW', 'REX', 'REXR', 'REYN', 'REZ', 'REZI', 'RF',
    'RFCI', 'RFDA', 'RFDI', 'RFEM', 'RFEU', 'RFFC', 'RFG', 'RFI',
    'RFIL', 'RFM', 'RFV', 'RGA', 'RGCO', 'RGEN', 'RGLD', 'RGLS',
    'RGNX', 'RGP', 'RGR', 'RGS', 'RGT', 'RH', 'RHI', 'RHP',
    'RICK', 'RIG', 'RIGL', 'RIGS', 'RILY', 'RIME', 'RINF', 'RING',
    'RIO', 'RIOT', 'RITM', 'RIV', 'RJF', 'RKDA', 'RL', 'RLGT',
    'RLI', 'RLJ', 'RLY', 'RM', 'RMAX', 'RMBI', 'RMBL', 'RMBS',
    'RMD', 'RMI', 'RMM', 'RMNI', 'RMR', 'RMT', 'RNAC', 'RNEM',
    'RNG', 'RNGR', 'RNP', 'RNR', 'RNRG', 'RNST', 'ROAD', 'ROAM',
    'ROBO', 'ROBT', 'ROCK', 'RODE', 'RODM', 'ROG', 'ROK', 'ROKT',
    'ROKU', 'ROL', 'ROM', 'ROMO', 'ROP', 'ROSC', 'ROST', 'ROUS',
    'RPAR', 'RPAY', 'RPD', 'RPG', 'RPM', 'RPT', 'RPV', 'RQI',
    'RRBI', 'RRC', 'RRGB', 'RRR', 'RRX', 'RS', 'RSF', 'RSG',
    'RSI', 'RSP', 'RSPC', 'RSPD', 'RSPF', 'RSPG', 'RSPH', 'RSPM',
    'RSPN', 'RSPR', 'RSPS', 'RSPT', 'RSPU', 'RSSS', 'RTH', 'RTO',
    'RTX', 'RUN', 'RUSHA', 'RVLV', 'RVMD', 'RVNU', 'RVSB', 'RVT',
    'RVTY', 'RWJ', 'RWK', 'RWL', 'RWM', 'RWO', 'RWR', 'RWT',
    'RWX', 'RXD', 'RXI', 'RXL', 'RY', 'RYAAY', 'RYAM', 'RYI',
    'RYLD', 'RYN', 'RYTM', 'RZG', 'RZLT', 'RZV', 'SA', 'SAA',
    'SABA', 'SABR', 'SAFE', 'SAFT', 'SAGE', 'SAH', 'SAIA', 'SAIC',
    'SAM', 'SAMG', 'SAN', 'SAND', 'SANG', 'SANM', 'SANW', 'SAP',
    'SAR', 'SATS', 'SB', 'SBAC', 'SBB', 'SBCF', 'SBEV', 'SBFG',
    'SBGI', 'SBH', 'SBI', 'SBIO', 'SBLK', 'SBR', 'SBRA', 'SBS',
    'SBSI', 'SBSW', 'SBUX', 'SCC', 'SCCO', 'SCD', 'SCHA', 'SCHB',
    'SCHC', 'SCHD', 'SCHE', 'SCHF', 'SCHG', 'SCHH', 'SCHI', 'SCHJ',
    'SCHK', 'SCHL', 'SCHM', 'SCHO', 'SCHP', 'SCHQ', 'SCHR', 'SCHV',
    'SCHW', 'SCHX', 'SCHZ', 'SCI', 'SCJ', 'SCL', 'SCM', 'SCNI',
    'SCO', 'SCOR', 'SCPH', 'SCS', 'SCSC', 'SCVL', 'SCZ', 'SD',
    'SDCI', 'SDD', 'SDEM', 'SDG', 'SDGR', 'SDIV', 'SDOG', 'SDOW',
    'SDP', 'SDS', 'SDVY', 'SDY', 'SE', 'SEB', 'SECT', 'SEDG',
    'SEE', 'SEF', 'SEI', 'SEIC', 'SEIX', 'SELF', 'SEM', 'SENEA',
    'SER', 'SEVN', 'SF', 'SFBC', 'SFBS', 'SFIX', 'SFL', 'SFM',
    'SFNC', 'SFST', 'SFY', 'SFYF', 'SFYX', 'SGA', 'SGC', 'SGDJ',
    'SGDM', 'SGI', 'SGML', 'SGOL', 'SGRY', 'SGU', 'SH', 'SHAG',
    'SHAK', 'SHBI', 'SHE', 'SHEL', 'SHEN', 'SHG', 'SHIP', 'SHM',
    'SHO', 'SHOO', 'SHOP', 'SHRY', 'SHV', 'SHW', 'SHY', 'SHYD',
    'SHYF', 'SHYG', 'SHYL', 'SIBN', 'SIEB', 'SIF', 'SIFY', 'SIG',
    'SIGA', 'SIGI', 'SII', 'SIJ', 'SIL', 'SILC', 'SILJ', 'SIM',
    'SIMO', 'SIMS', 'SINT', 'SIRI', 'SITC', 'SITE', 'SITM', 'SIVR',
    'SIXG', 'SIZE', 'SJB', 'SJM', 'SJNK', 'SJT', 'SJW', 'SKE',
    'SKF', 'SKIL', 'SKM', 'SKOR', 'SKT', 'SKX', 'SKY', 'SKYW',
    'SKYY', 'SLAB', 'SLB', 'SLDB', 'SLF', 'SLG', 'SLGN', 'SLM',
    'SLNG', 'SLNO', 'SLP', 'SLQD', 'SLRC', 'SLSN', 'SLV', 'SLVO',
    'SLVP', 'SLX', 'SLYG', 'SLYV', 'SM', 'SMB', 'SMBC', 'SMBK',
    'SMC', 'SMCI', 'SMDD', 'SMDV', 'SMFG', 'SMG', 'SMH', 'SMHB',
    'SMHI', 'SMID', 'SMIN', 'SMLF', 'SMLR', 'SMLV', 'SMMD', 'SMMT',
    'SMMU', 'SMMV', 'SMN', 'SMOG', 'SMP', 'SMPL', 'SMTC', 'SMTI',
    'SNA', 'SNAP', 'SNBR', 'SNCR', 'SND', 'SNDA', 'SNDR', 'SNDX',
    'SNES', 'SNEX', 'SNFCA', 'SNGX', 'SNN', 'SNOA', 'SNPE', 'SNPS',
    'SNSR', 'SNT', 'SNV', 'SNWV', 'SNX', 'SNY', 'SO', 'SOBR',
    'SOCL', 'SOGP', 'SOHU', 'SON', 'SONO', 'SONY', 'SOR', 'SOS',
    'SOTK', 'SOXL', 'SOXS', 'SOXX', 'SOYB', 'SPAB', 'SPB', 'SPBO',
    'SPCB', 'SPCE', 'SPDN', 'SPDV', 'SPDW', 'SPE', 'SPEM', 'SPEU',
    'SPFF', 'SPFI', 'SPG', 'SPGI', 'SPGM', 'SPGP', 'SPH', 'SPHB',
    'SPHD', 'SPHQ', 'SPHR', 'SPHY', 'SPIB', 'SPIP', 'SPLB', 'SPLG',
    'SPLP', 'SPLV', 'SPMB', 'SPMD', 'SPMO', 'SPMV', 'SPNS', 'SPNT',
    'SPOK', 'SPOT', 'SPPP', 'SPR', 'SPSB', 'SPSC', 'SPSK', 'SPSM',
    'SPT', 'SPTI', 'SPTL', 'SPTM', 'SPTN', 'SPTS', 'SPUS', 'SPUU',
    'SPVM', 'SPVU', 'SPXC', 'SPXE', 'SPXL', 'SPXN', 'SPXS', 'SPXT',
    'SPXU', 'SPXV', 'SPXX', 'SPY', 'SPYD', 'SPYG', 'SPYV', 'SPYX',
    'SQLV', 'SQM', 'SQNS', 'SQQQ', 'SR', 'SRCE', 'SRDX', 'SRE',
    'SRET', 'SRG', 'SRI', 'SRL', 'SRLN', 'SRPT', 'SRRK', 'SRS',
    'SRTS', 'SRTY', 'SRV', 'SRVR', 'SSB', 'SSBI', 'SSD', 'SSG',
    'SSKN', 'SSL', 'SSNC', 'SSO', 'SSP', 'SSPY', 'SSRM',
    'SSSS', 'SSTI', 'SSTK', 'SSUS', 'SSYS', 'ST', 'STAA', 'STAG',
    'STBA', 'STC', 'STE', 'STEL', 'STEW', 'STG', 'STGW', 'STIM',
    'STIP', 'STK', 'STKL', 'STKS', 'STLA', 'STLD', 'STM', 'STN',
    'STNE', 'STNG', 'STOK', 'STOT', 'STPZ', 'STR', 'STRA', 'STRL',
    'STRM', 'STRR', 'STRS', 'STRT', 'STT', 'STWD', 'STX', 'STZ',
    'SU', 'SUB', 'SUI', 'SUN', 'SUNE', 'SUP', 'SUPN', 'SUPV',
    'SURE', 'SURG', 'SUSA', 'SUSB', 'SUSC', 'SUSL', 'SUZ', 'SVM',
    'SVRA', 'SVT', 'SVXY', 'SW', 'SWAN', 'SWBI', 'SWI', 'SWK',
    'SWKH', 'SWKS', 'SWTX', 'SWX', 'SWZ', 'SXC', 'SXI', 'SXT',
    'SXTC', 'SYBT', 'SYF', 'SYK', 'SYLD', 'SYNA', 'SYRE', 'SYY',
    'SZK', 'SZNE', 'T', 'TAC', 'TACT', 'TAGS', 'TAIL', 'TAIT',
    'TAK', 'TAL', 'TALO', 'TAN', 'TANH', 'TAP', 'TARA', 'TATT',
    'TAXF', 'TAYD', 'TBBK', 'TBCH', 'TBF', 'TBI', 'TBLL', 'TBLU',
    'TBPH', 'TBRG', 'TBT', 'TBX', 'TCBI', 'TCBK', 'TCI', 'TCMD',
    'TCOM', 'TCPC', 'TCRT', 'TCX', 'TD', 'TDC', 'TDF', 'TDG',
    'TDIV', 'TDOC', 'TDS', 'TDTF', 'TDTT', 'TDV', 'TDW', 'TDY',
    'TEAF', 'TEAM', 'TECB', 'TECH', 'TECK', 'TECL', 'TECS', 'TECTP',
    'TECX', 'TEF', 'TEI', 'TEL', 'TEN', 'TENB', 'TENX', 'TEO',
    'TER', 'TEVA', 'TEX', 'TFC', 'TFI', 'TFII', 'TFIN', 'TFLO',
    'TFSL', 'TFX', 'TG', 'TGB', 'TGI', 'TGLS', 'TGNA', 'TGS',
    'TGT', 'TGTX', 'TH', 'THC', 'THD', 'THFF', 'THG', 'THO',
    'THQ', 'THR', 'THRM', 'THRY', 'THS', 'THTX', 'THW', 'TIGO',
    'TIGR', 'TILE', 'TILT', 'TIMB', 'TIP', 'TIPT', 'TIPX', 'TIPZ',
    'TISI', 'TITN', 'TJX', 'TK', 'TKC', 'TKO', 'TKR', 'TLF',
    'TLH', 'TLK', 'TLT', 'TLTD', 'TLTE', 'TM', 'TMDV', 'TMDX',
    'TME', 'TMF', 'TMFC', 'TMFS', 'TMHC', 'TMO', 'TMP', 'TMUS',
    'TMV', 'TNA', 'TNC', 'TNDM', 'TNET', 'TNK', 'TNL', 'TNXP',
    'TOK', 'TOKE', 'TOL', 'TOLZ', 'TOPS', 'TOTL', 'TOWN', 'TPB',
    'TPC', 'TPCS', 'TPH', 'TPHD', 'TPIF', 'TPL', 'TPLC', 'TPOR',
    'TPR', 'TPSC', 'TPST', 'TPVG', 'TPYP', 'TPZ', 'TQQQ', 'TR',
    'TRAK', 'TRC', 'TREE', 'TREX', 'TRGP', 'TRI', 'TRIP', 'TRMB',
    'TRMD', 'TRMK', 'TRN', 'TRND', 'TRNO', 'TRNS', 'TROW', 'TROX',
    'TRP', 'TRPA', 'TRS', 'TRST', 'TRT', 'TRTX', 'TRTY', 'TRU',
    'TRUP', 'TRV', 'TRVG', 'TRVI', 'TS', 'TSAT', 'TSBK', 'TSCO',
    'TSE', 'TSEM', 'TSI', 'TSLA', 'TSLX', 'TSM', 'TSN', 'TSQ',
    'TSSI', 'TT', 'TTC', 'TTD', 'TTE', 'TTEC', 'TTEK', 'TTGT',
    'TTI', 'TTMI', 'TTNP', 'TTSH', 'TTT', 'TTWO', 'TU', 'TUR',
    'TURN', 'TUSK', 'TVRD', 'TVTX', 'TW', 'TWI', 'TWIN', 'TWLO',
    'TWM', 'TWN', 'TWO', 'TWST', 'TX', 'TXG', 'TXN', 'TXNM',
    'TXRH', 'TXT', 'TY', 'TYD', 'TYG', 'TYL', 'TYO', 'TZA',
    'TZOO', 'UA', 'UAA', 'UAE', 'UAL', 'UAMY', 'UAN', 'UAPR',
    'UAUG', 'UBCP', 'UBER', 'UBFO', 'UBOT', 'UBR', 'UBS', 'UBSI',
    'UBT', 'UCB', 'UCC', 'UCIB', 'UCO', 'UCON', 'UCTT', 'UDEC',
    'UDIV', 'UDN', 'UDOW', 'UDR', 'UE', 'UEC', 'UEIC', 'UEVM',
    'UFCS', 'UFEB', 'UFI', 'UFO', 'UFPI', 'UFPT', 'UG', 'UGA',
    'UGE', 'UGI', 'UGL', 'UGP', 'UHAL', 'UHS', 'UHT', 'UI',
    'UIS', 'UITB', 'UIVM', 'UJAN', 'UJB', 'UJUL', 'UJUN', 'UL',
    'ULBI', 'ULE', 'ULH', 'ULST', 'ULTA', 'ULVM', 'UMAR', 'UMBF',
    'UMC', 'UMDD', 'UMH', 'UNB', 'UNF', 'UNFI', 'UNG', 'UNH',
    'UNIT', 'UNL', 'UNM', 'UNOV', 'UNP', 'UNTY', 'UOCT', 'UPBD',
    'UPGD', 'UPLD', 'UPRO', 'UPS', 'UPV', 'UPW', 'UPWK', 'URA',
    'URBN', 'URE', 'URGN', 'URI', 'URNM', 'URTH', 'URTY', 'USA',
    'USAC', 'USAI', 'USAU', 'USB', 'USCI', 'USD', 'USDU', 'USEP',
    'USFD', 'USFR', 'USHY', 'USIG', 'USL', 'USLM', 'USM', 'USMC',
    'USMF', 'USMV', 'USNA', 'USO', 'USOI', 'USPH', 'USPX', 'USRT',
    'USSG', 'UST', 'USTB', 'USVM', 'UTES', 'UTF', 'UTG', 'UTHR',
    'UTI', 'UTL', 'UTMD', 'UTSI', 'UTSL', 'UTZ', 'UUP', 'UUU',
    'UUUU', 'UVE', 'UVSP', 'UVV', 'UVXY', 'UWM', 'UWMC', 'UXI',
    'UXIN', 'UYG', 'UYM', 'V', 'VABK', 'VAC', 'VALE', 'VALQ',
    'VALU', 'VAMO', 'VATE', 'VAW', 'VB', 'VBF', 'VBK', 'VBND',
    'VBNK', 'VBR', 'VBTX', 'VC', 'VCEL', 'VCIT', 'VCLT', 'VCR',
    'VCSH', 'VCTR', 'VCV', 'VCYT', 'VDC', 'VDE', 'VEA', 'VECO',
    'VEEV', 'VEGA', 'VEGI', 'VEGN', 'VEL', 'VEON', 'VERB', 'VERI',
    'VERO', 'VET', 'VEU', 'VFC', 'VFH', 'VFL', 'VFMF', 'VFMO',
    'VFMV', 'VFQY', 'VFVA', 'VGI', 'VGIT', 'VGK', 'VGLT', 'VGM',
    'VGSH', 'VGT', 'VHC', 'VHI', 'VHT', 'VIAV', 'VICE', 'VICI',
    'VICR', 'VIDI', 'VIG', 'VIGI', 'VIOG', 'VIOO', 'VIOV', 'VIPS',
    'VIR', 'VIRC', 'VIRT', 'VIS', 'VIST', 'VIV', 'VIXM', 'VIXY',
    'VKI', 'VKQ', 'VKTX', 'VLGEA', 'VLO', 'VLRS', 'VLT', 'VLU',
    'VLUE', 'VLY', 'VMBS', 'VMC', 'VMD', 'VMI', 'VMO', 'VNDA',
    'VNET', 'VNLA', 'VNM', 'VNO', 'VNOM', 'VNQ', 'VNQI', 'VO',
    'VOC', 'VOD', 'VOE', 'VONE', 'VONG', 'VONV', 'VOO', 'VOOG',
    'VOOV', 'VOT', 'VOX', 'VOYA', 'VPC', 'VPG', 'VPL', 'VPU',
    'VPV', 'VRAI', 'VRDN', 'VRE', 'VREX', 'VRIG', 'VRN', 'VRNA',
    'VRNS', 'VRNT', 'VRP', 'VRRM', 'VRSK', 'VRSN', 'VRT', 'VRTS',
    'VRTX', 'VS', 'VSAT', 'VSDA', 'VSEC', 'VSGX', 'VSH', 'VSHY',
    'VSMV', 'VSS', 'VST', 'VSTM', 'VT', 'VTC', 'VTEB', 'VTGN',
    'VTHR', 'VTI', 'VTIP', 'VTLE', 'VTN', 'VTOL', 'VTR', 'VTRS',
    'VTSI', 'VTV', 'VTVT', 'VTWG', 'VTWO', 'VTWV', 'VUG', 'VUSE',
    'VV', 'VVPR', 'VVR', 'VVV', 'VVX', 'VWID', 'VWO', 'VWOB',
    'VXF', 'VXUS', 'VXX', 'VXZ', 'VYGR', 'VYM', 'VYMI', 'VYX',
    'VZ', 'VZLA', 'W', 'WAB', 'WABC', 'WAFD', 'WAL', 'WANT',
    'WASH', 'WAT', 'WB', 'WBA', 'WBD', 'WBIF', 'WBIG', 'WBIL',
    'WBIY', 'WBND', 'WBS', 'WCC', 'WCLD', 'WCN', 'WD', 'WDAY',
    'WDC', 'WDFC', 'WDIV', 'WDS', 'WEA', 'WEAT', 'WEBL', 'WEBS',
    'WEC', 'WELL', 'WEN', 'WERN', 'WES', 'WEX', 'WEYS', 'WF',
    'WFC', 'WFCF', 'WFG', 'WFRD', 'WGO', 'WH', 'WHD', 'WHF',
    'WHG', 'WHR', 'WIA', 'WILC', 'WIMI', 'WINA', 'WINC', 'WING',
    'WIP', 'WIT', 'WIW', 'WIX', 'WK', 'WKC', 'WKEY', 'WKSP',
    'WLDN', 'WLDR', 'WLFC', 'WLK', 'WLKP', 'WLY', 'WM', 'WMB',
    'WMK', 'WMPN', 'WMS', 'WMT', 'WNC', 'WNEB', 'WNS', 'WOLF',
    'WOMN', 'WOOD', 'WOR', 'WOW', 'WPC', 'WPM', 'WPP', 'WPRT',
    'WRB', 'WRLD', 'WSBC', 'WSBF', 'WSC', 'WSFS', 'WSM', 'WSO',
    'WSR', 'WST', 'WT', 'WTBA', 'WTFC', 'WTM', 'WTMF', 'WTPI',
    'WTRE', 'WTRG', 'WTS', 'WTTR', 'WTV', 'WTW', 'WU', 'WUGI',
    'WULF', 'WVE', 'WVVI', 'WWD', 'WWJD', 'WWW', 'WY', 'WYNN',
    'WYY', 'X', 'XAR', 'XBI', 'XBIO', 'XBIT', 'XCEM', 'XCUR',
    'XEL', 'XELB', 'XENE', 'XERS', 'XES', 'XFLT', 'XGN', 'XHB',
    'XHE', 'XHR', 'XHS', 'XIFR', 'XIN', 'XITK', 'XLB', 'XLC',
    'XLE', 'XLF', 'XLG', 'XLI', 'XLK', 'XLP', 'XLRE', 'XLSR',
    'XLU', 'XLV', 'XLY', 'XME', 'XMHQ', 'XMLV', 'XMMO', 'XMPT',
    'XMVM', 'XNCR', 'XNET', 'XNTK', 'XOM', 'XOMA', 'XOP', 'XOVR',
    'XP', 'XPEL', 'XPER', 'XPH', 'XPO', 'XPP', 'XPRO', 'XRAY',
    'XRLV', 'XRT', 'XRX', 'XSD', 'XSHD', 'XSHQ', 'XSLV', 'XSMO',
    'XSOE', 'XSVM', 'XSW', 'XT', 'XTL', 'XTN', 'XYF', 'XYL',
    'XYLD', 'XYLO', 'XYZ', 'YANG', 'YCL', 'YCS', 'YELP', 'YETI',
    'YEXT', 'YI', 'YINN', 'YLD', 'YLDE', 'YMAB', 'YORW', 'YPF',
    'YRD', 'YUM', 'YUMC', 'YXI', 'YYY', 'Z', 'ZBH', 'ZBRA',
    'ZD', 'ZDGE', 'ZEPP', 'ZEUS', 'ZG', 'ZIG', 'ZION', 'ZLAB',
    'ZM', 'ZROZ', 'ZS', 'ZSL', 'ZTO', 'ZTR', 'ZTS', 'ZUMZ',
    'ZVRA', 'ZWS', 'ZYME', 'ZYXI',
    )

ivy_watchlist = FULL_LIST + composite_index + small_cap + active_trading_index
ivy_watchlist = sorted(set(ivy_watchlist))
# skipping = True
# skippable_list = list()
# for v in ivy_watchlist:
    # if skipping and v[0] != 'U':
        # continue
    # else:
        # skipping = False
    # skippable_list.append(v)
# ivy_watchlist = skippable_list
