ivy_watchlist = (
    'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACN', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AEP',
    'AIG', 'ALGN', 'AMAT', 'AMD', 'AMGN', 'AMT', 'AMZN', 'ANSS', 'ASML', 'ATVI',
    'AVGO', 'AXP', 'AZN', 'BA', 'BAC', 'BIIB', 'BK', 'BKNG', 'BKR', 'BLK',
    'BMY', 'BRK.B', 'C', 'CAT', 'CDNS', 'CEG', 'CHTR', 'CL', 'CMCSA', 'COF',
    'COP', 'COST', 'CPRT', 'CRM', 'CRWD', 'CSCO', 'CSGP', 'CSX', 'CTAS',
    'CTSH', 'CVS', 'CVX', 'DDOG', 'DHR', 'DIS', 'DLTR', 'DOW', 'DUK', 'DXCM',
    'EA', 'EBAY', 'EMR', 'ENPH', 'EXC', 'F', 'FANG', 'FAST', 'FDX', 'FISV',
    'FTNT', 'GD', 'GE', 'GFS', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD',
    'HON', 'IBM', 'IDXX', 'ILMN', 'INTC', 'INTU', 'ISRG', 'JD', 'JNJ', 'JPM',
    'KDP', 'KHC', 'KLAC', 'KO', 'LCID', 'LIN', 'LLY', 'LMT', 'LOW', 'LRCX',
    'LULU', 'MA', 'MAR', 'MCD', 'MCHP', 'MDLZ', 'MDT', 'MELI', 'MET', 'META',
    'MMM', 'MNST', 'MO', 'MRK', 'MRNA', 'MRVL', 'MS', 'MSFT', 'MU', 'NEE',
    'NFLX', 'NKE', 'NVDA', 'NXPI', 'ODFL', 'ORCL', 'ORLY', 'PANW', 'PAYX',
    'PCAR', 'PDD', 'PEP', 'PFE', 'PG', 'PM', 'PYPL', 'QCOM', 'REGN', 'RIVN',
    'ROST', 'RTX', 'SBUX', 'SCHW', 'SGEN', 'SIRI', 'SNPS', 'SO', 'SPG', 'T',
    'TEAM', 'TGT', 'TMO', 'TMUS', 'TSLA', 'TXN', 'UNH', 'UNP', 'UPS', 'USB',
    'V', 'VRSK', 'VRTX', 'VZ', 'WBA', 'WBD', 'WDAY', 'WFC', 'WMT', 'XEL',
    'XOM', 'ZM', 'ZS',
    )
